<?xml version = '1.0' encoding = 'utf-8'?>
<!-- $Header: TEMPLATE_XXSC_XXSC_STATEMENT_OF_SERVICE_en.xsl 115.0 2016/05/23 09:25:40 xdouser noship $ -->
<!-- dbdrv: none -->

<!--Generated by Oracle BI Publisher 10.1.3.4.2-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="66.6pt" margin-right="66.6pt" page-height="792.0pt" page-width="612.0pt" margin-top="36.0pt" margin-bottom="0.0pt">
               <fo:region-before region-name="region-header" extent="36.0pt"/>
               <fo:region-body region-name="region-body" margin-top="36.0pt" margin-bottom="72.0pt"/>
               <fo:region-after region-name="region-footer" extent="72.0pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(612.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(792.0)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(0.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header">
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="justify" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt"/>
               <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
               <xsl:for-each select=".//G_EMP_DETAILS_GROUP">
                  <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                  <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                  <fo:block xdofo:tab-stops="center:234.0pt:space right:468.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="13.392pt"/>
               </xsl:for-each>
               <fo:block xdofo:tab-stops="center:234.0pt:space right:468.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="13.392pt"/>
            </fo:static-content>
            <fo:static-content flow-name="region-footer">
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="justify" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt"/>
            </fo:static-content>
            <fo:flow flow-name="region-body">
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="13.392pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="13.392pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="13.392pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="13.392pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="13.392pt"/>
               <fo:block xdofo:xliff-note="TODAY_DATE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">
                     <xsl:value-of select=".//TODAY_DATE" xdofo:field-name="TODAY_DATE"/>
                  </fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="center" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline xml:space="preserve" white-space-collapse="false" font-weight="bold" height="19.04pt" font-family="Calibri" text-decoration="underline" font-size="16.0pt">To Whomever It May Concern</fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="justify" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="justify" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block xdofo:xliff-note="PERSON_NAME" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="justify" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline xml:space="preserve" height="14.280001pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" font-weight="bold">STATEMENT OF SERVICE – <xsl:value-of select=".//PERSON_NAME" xdofo:field-name="PERSON_NAME"/></fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="justify" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block xdofo:xliff-note="PERSON_NAME, NATIONALITY, NATIONAL_IDENTIFIER, LEGAL_EMPLOYER, JOB_NAME, DEPARTMENT" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">This letter confirms that </fo:inline>
                  <fo:inline height="14.280001pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" font-weight="bold">
                     <xsl:value-of select=".//PERSON_NAME" xdofo:field-name="PERSON_NAME"/>
                  </fo:inline>
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">,</fo:inline>
                  <fo:inline xml:space="preserve" height="14.280001pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" font-weight="bold"> </fo:inline>
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">holder of <xsl:value-of select=".//NATIONALITY" xdofo:field-name="NATIONALITY"/> passport number </fo:inline>
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" color="#000000">
                     <xsl:value-of select=".//NATIONAL_IDENTIFIER" xdofo:field-name="NATIONAL_IDENTIFIER"/>
                  </fo:inline>
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt"> was employed by </fo:inline>
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" color="#000000"><xsl:value-of select=".//LEGAL_EMPLOYER" xdofo:field-name="LEGAL_EMPLOYER"/> </fo:inline>
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">in the capacity of <xsl:value-of select=".//JOB_NAME" xdofo:field-name="JOB_NAME"/>  -  <xsl:value-of select=".//DEPARTMENT" xdofo:field-name="DEPARTMENT"/>.</fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block xdofo:xliff-note="LEGAL_EMPLOYER" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">Below are the details of his/her employment with </fo:inline>
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" color="#000000">
                     <xsl:value-of select=".//LEGAL_EMPLOYER" xdofo:field-name="LEGAL_EMPLOYER"/>
                  </fo:inline>
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">:</fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block xdofo:xliff-note="EFFECTIVE_START_DATE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">Start Date</fo:inline>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">: <xsl:value-of select=".//EFFECTIVE_START_DATE" xdofo:field-name="EFFECTIVE_START_DATE"/></fo:inline>
               </fo:block>
               <fo:block xdofo:xliff-note="EFFECTIVE_END_DATE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">Final Date</fo:inline>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">: <xsl:value-of select=".//EFFECTIVE_END_DATE" xdofo:field-name="EFFECTIVE_END_DATE"/></fo:inline>
               </fo:block>
               <fo:block xdofo:xliff-note="GRADE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">Grade   </fo:inline>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">: </fo:inline>
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" color="#000000">
                     <xsl:value-of select=".//GRADE" xdofo:field-name="GRADE"/>
                  </fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">Sincerely</fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="12.0pt" height="13.872pt"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt"> </fo:inline>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">________________________</fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" background-color="#ffff00">[Signatory]</fo:inline>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <fo:inline xml:space="preserve" height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt">Company Stamp</fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <fo:inline height="13.872pt" font-family="Calibri" white-space-collapse="false" font-size="12.0pt" background-color="#ffff00">[Business Title]</fo:inline>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt">
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="12.0pt" font-family="Calibri"/>
               </fo:block>
               <fo:block xdofo:tab-stops="left:45.8pt:space left:91.6pt:space left:137.4pt:space left:183.2pt:space left:229.0pt:space left:274.8pt:space left:320.6pt:space left:366.4pt:space left:412.2pt:space left:458.0pt:space left:503.8pt:space left:549.6pt:space left:595.4pt:space left:641.2pt:space left:687.0pt:space left:732.8pt:space" xdofo:line-spacing="at-least:13.5pt" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="7.5pt" end-indent="5.4pt" padding-top="7.5pt" font-family="Courier New" font-size="9.0pt" height="0.0pt" background-color="#ffffff"/>
               <fo:block xdofo:tab-stops="left:45.8pt:space left:91.6pt:space left:137.4pt:space left:183.2pt:space left:229.0pt:space left:274.8pt:space left:320.6pt:space left:366.4pt:space left:412.2pt:space left:458.0pt:space left:503.8pt:space left:549.6pt:space left:595.4pt:space left:641.2pt:space left:687.0pt:space left:732.8pt:space" xdofo:line-spacing="at-least:13.5pt" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="7.5pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Courier New" font-size="9.0pt" height="0.0pt" background-color="#ffffff"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="13.392pt">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
