<?xml version = '1.0' encoding = 'utf-8'?>
<!-- $Header: TEMPLATE_XXSC_XXSC_ELE_PAY_RUN_RES_en.xsl 115.0 2016/05/23 09:25:40 xdouser noship $ -->
<!-- dbdrv: none -->

<!--Generated by Oracle BI Publisher 10.1.3.4.2-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="23.4pt" margin-right="23.4pt" page-height="648.0pt" page-width="1584.0pt" margin-top="27.35pt" margin-bottom="18.0pt">
               <fo:region-before region-name="region-header" extent="0.0pt"/>
               <fo:region-body region-name="region-body" margin-top="0.0pt" margin-bottom="0.0pt"/>
               <fo:region-after region-name="region-footer" extent="0.0pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(1584.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(648.0)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(28.8)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(28.8)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(27.35)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(18.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(27.35)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(18.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header">
               <fo:block padding-bottom="0.25pt" padding-top="0.25pt">
                  <fo:table start-indent="167.4pt" style-id="ts15" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="306.0pt"/>
                     <fo:table-column column-width="274.5pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                 <fo:inline xml:space="preserve" height="8.0pt" font-family="Calibri" white-space-collapse="false" font-size="8.0pt"><xsl:value-of select="xdoxslt:sysdate(&quot;d-MMM-yy&quot;,2)" xdofo:field-name="xdoxslt:sysdate(&quot;d-MMM-yy&quot;, 2)"/> </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block padding-bottom="0.0pt" text-align="right" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="8.0pt" font-family="Calibri" white-space-collapse="false" font-size="8.0pt">Page <fo:page-number/> of <fo:page-number-citation ref-id="xdofo:lastpage-joinseq"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block padding-bottom="0.0pt" text-align="center" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="10.710001pt" font-family="Calibri" font-size="9.0pt"/>
            </fo:static-content>
            <fo:static-content flow-name="region-footer">
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
            </fo:static-content>
            <fo:flow flow-name="region-body">
               <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="center" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="0pt">
                  <fo:inline xml:space="preserve" height="10.404pt" font-family="Calibri" white-space-collapse="false" font-size="9.0pt" color="#000080"> </fo:inline>
               </fo:block>
               <fo:block padding-bottom="0.0pt" text-align="center" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve">
                  <fo:table start-indent="167.4pt" style-id="ts15" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 2" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="580.5pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.25pt" number-columns-spanned="1">
                              <fo:block padding-bottom="0.0pt" text-align="center" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                 <fo:inline font-size="20.0pt" white-space-collapse="false" height="20.0pt" font-family="Calibri" font-weight="bold">Payroll Element Run Sheet Report</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.25pt" number-columns-spanned="1">
                              <fo:block xdofo:xliff-note="PAYROLL_PERIOD, F " padding-bottom="0.0pt" text-align="center" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" font-size="9.0pt" white-space-collapse="false" height="9.0pt" font-family="Calibri" font-weight="bold">Payroll Period : <xsl:value-of select=".//PERIOD_NAME" xdofo:field-name="PERIOD_NAME"/></fo:inline>
                                 <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_EAR',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_EAR', 0)"/>
                                 <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_V_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_V_DED', 0)"/>
                                 <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_IV_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_IV_DED', 0)"/>
                                 <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_NET',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_NET', 0)"/>
                                 <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" color="#000080"/>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="10.404pt" font-family="Calibri" font-size="9.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.25pt" text-align="start" orphans="2" widows="2" padding-top="0.25pt" end-indent="5.4pt" linefeed-treatment="preserve">
                  <xdofo:horizontal-break-table row-header-count="1" xdofo:status="1">
                     <fo:table start-indent="0.0pt" style-id="ts15" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 3" xdofo:row-header-count="1">
                        <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                        <xsl:variable name="_XDOFOTOTAL" select="count(.//G_EMP_DETAILS_GROUP)"/>
                        <fo:table-column column-width="23.2pt"/>
                        <fo:table-column column-width="37.05pt"/>
                        <fo:table-column column-width="37.05pt"/>
                        <fo:table-column column-width="34.8pt"/>
                        <fo:table-column column-width="93.25pt"/>
                        <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                        <xsl:for-each-group select=".//G_EMP_DETAILS_GROUP" group-by=".//ELEMENT_NAME" xdofo:ctx="20" xdofo:start-idx="5" xdofo:end-idx="5">
                           <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                           <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                           <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                           <xsl:variable name="_XDOFOTOTAL" select="count(.//G_EMP_DETAILS_GROUP)"/>
                           <xsl:for-each-group select=".//G_EMP_DETAILS_GROUP" group-by=".//ELEMENT_NAME" xdofo:ctx="20" xdofo:start-idx="5" xdofo:end-idx="5">
                              <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                              <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                              <fo:table-column column-width="93.25pt"/>
                           </xsl:for-each-group>
                        </xsl:for-each-group>
                        <fo:table-column column-width="93.25pt"/>
                        <fo:table-column column-width="93.25pt"/>
                        <fo:table-column column-width="93.25pt"/>
                        <fo:table-column column-width="93.25pt"/>
                        <fo:table-header>
                           <fo:table-row keep-with-next="always">
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" font-weight="bold" font-style="italic">Department</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" font-weight="bold" font-style="italic">Payment Method</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" font-weight="bold" font-style="italic">Employee Number</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" font-weight="bold" font-style="italic">Full Name</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Hire Date</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                              <xsl:variable name="_XDOFOTOTAL" select="count(.//G_EMP_DETAILS_GROUP)"/>
                              <xsl:for-each-group select=".//G_EMP_DETAILS_GROUP" group-by=".//ELEMENT_NAME" xdofo:ctx="20" xdofo:start-idx="5" xdofo:end-idx="5">
                                 <xsl:sort select=".//CLASSIFICATION_NAME"/>
                                 <xsl:sort xdofo:ctx="6" select="RESULT_VALUE" order="descending"/>
                                 <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                                 <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd">
                                    <fo:block xdofo:xliff-note="header coulmn, for:, CLASSIFICATION_NAME, end" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                       <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"> </fo:inline>
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">
                                          <xsl:value-of select=".//CLASSIFICATION_NAME" xdofo:field-name="CLASSIFICATION_NAME"/>
                                       </fo:inline>
                                       <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"> </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                              </xsl:for-each-group>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Total Earnings</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Total Voluntary Deductions</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Involuntary Deductions</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd" number-rows-spanned="2">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Net Payment</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-with-next="always">
                              <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                              <xsl:variable name="_XDOFOTOTAL" select="count(.//G_EMP_DETAILS_GROUP)"/>
                              <xsl:for-each-group select=".//G_EMP_DETAILS_GROUP" group-by=".//ELEMENT_NAME" xdofo:ctx="20" xdofo:start-idx="5" xdofo:end-idx="5">
                                 <xsl:sort select=".//CLASSIFICATION_NAME"/>
                                 <xsl:sort xdofo:ctx="6" select="RESULT_VALUE" order="descending"/>
                                 <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                                 <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="116.8pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd">
                                    <fo:block xdofo:xliff-note="for:, ELEMENT_NAME, end" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                       <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"> </fo:inline>
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">
                                          <xsl:value-of select=".//ELEMENT_NAME" xdofo:field-name="ELEMENT_NAME"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                              </xsl:for-each-group>
                           </fo:table-row>
                        </fo:table-header>
                        <fo:table-body>
                           <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                           <xsl:variable name="_XDOFOTOTAL" select="count(.//G_EMP_DETAILS_GROUP)"/>
                           <xsl:for-each-group select=".//G_EMP_DETAILS_GROUP" group-by="./EMPLOYEE_NUMBER" xdofo:ctx="3">
                              <xsl:variable name="EMP" select=".//EMPLOYEE_NUMBER"/>
                              <xsl:variable name="ELE" select=".//ELEMENT_NAME"/>
                              <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                              <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                              <fo:table-row xdofo:repeat="R">
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="F , BUSINESS UNIT" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0.0pt">
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_EAR',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_EAR', 0)"/>
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_V_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_V_DED', 0)"/>
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_IV_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_IV_DED', 0)"/>
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT', 0)"/>
                                       <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" color="#000080"/>
                                       <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt">
                                          <xsl:value-of select=".//BUSINESS_UNIT" xdofo:field-name="BUSINESS_UNIT"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="Payment Method" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt">
                                          <xsl:value-of select=".//PAYMENT_METHOD" xdofo:field-name="PAYMENT_METHOD"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="EMPLOYEE_NUMBER" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt">
                                          <xsl:value-of select=".//EMPLOYEE_NUMBER" xdofo:field-name="EMPLOYEE_NUMBER"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="NAME" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt">
                                          <xsl:value-of select=".//NAME" xdofo:field-name="NAME"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="ORIGINAL_DATE_OF_HIRE" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                          <xsl:value-of select=".//ORIGINAL_DATE_OF_HIRE" xdofo:field-name="ORIGINAL_DATE_OF_HIRE"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                                 <xsl:variable name="_XDOFOTOTAL" select="count(//G_EMP_DETAILS_GROUP)"/>
                                 <xsl:for-each-group select="//G_EMP_DETAILS_GROUP" group-by="./ELEMENT_NAME" xdofo:ctx="21" xdofo:start-idx="5" xdofo:end-idx="5">
                                    <xsl:sort select=".//CLASSIFICATION_NAME"/>
                                    <xsl:sort xdofo:ctx="6" select="RESULT_VALUE" order="descending"/>
                                    <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                                    <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                                    <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                       <fo:block xdofo:xliff-note="for: ,      , end" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                          <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                             <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv1">
                                                <xsl:value-of select="sum(current-group()[.//EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)" xdofo:field-name="sum(current-group()[EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)"/>
                                             </xsl:variable>
                                             <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv1, '0.00')"/>
                                          </fo:inline>
                                       </fo:block>
                                    </fo:table-cell>
                                 </xsl:for-each-group>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                       <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"><xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv2"><xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Earnings'])" xdofo:ctx="17"><xsl:value-of select="sum(current-group()[.//EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)" xdofo:field-name="sum(current-group()[EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)"/><xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_EAR',xdoxslt:get_variable($_XDOCTX,'RTOT_EAR') + (sum(current-group()[.//EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_EAR',xdoxslt:get_variable($_XDOCTX, 'RTOT_EAR')+(sum(current-group()[EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)))"/></xsl:if></xsl:variable><xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv2, '0.00')"/> </fo:inline>
                                    </fo:block>
                                    <xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Earnings'])" xdofo:ctx="3">
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_EAR',xdoxslt:get_variable($_XDOCTX,'TOT_EAR') + (sum(current-group()[.//EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_EAR',xdoxslt:get_variable($_XDOCTX, 'TOT_EAR')+(sum(current-group()[EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)))"/>
                                    </xsl:if>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     , RESULT_VALUE" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                          <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv3">
                                             <xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Voluntary Deductions'])" xdofo:ctx="17">
                                                <xsl:value-of select="sum(current-group()[.//EMPLOYEE_NUMBER=$EMP][.//CLASSIFICATION_NAME='Voluntary Deductions']/RESULT_VALUE)" xdofo:field-name="sum(current-group()[EMPLOYEE_NUMBER=$EMP][CLASSIFICATION_NAME='Voluntary Deductions']/RESULT_VALUE)"/>
                                                <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_V_DED',(sum(current-group()[.//CLASSIFICATION_NAME='Voluntary Deductions'][.//EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_V_DED',(sum(current-group()[CLASSIFICATION_NAME='Voluntary Deductions'][EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)))"/>
                                             </xsl:if>
                                          </xsl:variable>
                                          <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv3, '0.00')"/>
                                       </fo:inline>
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_V_DED',xdoxslt:get_variable($_XDOCTX,'TOT_V_DED') + xdoxslt:get_variable($_XDOCTX,'RTOT_V_DED'))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_V_DED',xdoxslt:get_variable($_XDOCTX, 'TOT_V_DED')+xdoxslt:get_variable($_XDOCTX, 'RTOT_V_DED'))"/>
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"/>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                          <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv4">
                                             <xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Involuntary Deductions'])" xdofo:ctx="17">
                                                <xsl:value-of select="sum(current-group()[.//EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)" xdofo:field-name="sum(current-group()[EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE)"/>
                                                <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_IV_DED',xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED') + sum(current-group()[.//EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_IV_DED', xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED') + sum(current-group()[EMPLOYEE_NUMBER=$EMP]/RESULT_VALUE))"/>
                                             </xsl:if>
                                          </xsl:variable>
                                          <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv4, '0.00')"/>
                                       </fo:inline>
                                    </fo:block>
                                    <xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Involuntary Deductions'])" xdofo:ctx="3">
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_IV_DED',xdoxslt:get_variable($_XDOCTX,'TOT_IV_DED') + xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED'))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_IV_DED', xdoxslt:get_variable($_XDOCTX,'TOT_IV_DED') +xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED'))"/>
                                    </xsl:if>
                                 </fo:table-cell>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     , RESULT_VALUE, E" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                          <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv5">
                                             <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT',xdoxslt:get_variable($_XDOCTX,'RTOT_EAR') - xdoxslt:get_variable($_XDOCTX,'RTOT_V_DED') - xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED'))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT', xdoxslt:get_variable($_XDOCTX,'RTOT_EAR') - xdoxslt:get_variable($_XDOCTX,'RTOT_V_DED') - xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED'))"/>
                                             <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'RTOT')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX,'RTOT')"/>
                                             <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_EAR',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_EAR', 0)"/>
                                             <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_V_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_V_DED', 0)"/>
                                          </xsl:variable>
                                          <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv5, '0.00')"/>
                                       </fo:inline>
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_NET',xdoxslt:get_variable($_XDOCTX,'TOT_NET') + xdoxslt:get_variable($_XDOCTX,'RTOT'))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_NET', xdoxslt:get_variable($_XDOCTX, 'TOT_NET') +xdoxslt:get_variable($_XDOCTX, 'RTOT'))"/>
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"/>
                                       <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_IV_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_IV_DED', 0)"/>
                                       <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" color="#000080"/>
                                    </fo:block>
                                 </fo:table-cell>
                              </fo:table-row>
                           </xsl:for-each-group>
                           <fo:table-row>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block height="12.0pt"/>
                              </fo:table-cell>
                              <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                              <xsl:variable name="_XDOFOTOTAL" select="count(//G_EMP_DETAILS_GROUP)"/>
                              <xsl:for-each-group select="//G_EMP_DETAILS_GROUP" group-by="./ELEMENT_NAME" xdofo:ctx="21" xdofo:start-idx="5" xdofo:end-idx="5">
                                 <xsl:sort select=".//CLASSIFICATION_NAME"/>
                                 <xsl:sort xdofo:ctx="6" select="RESULT_VALUE" order="descending"/>
                                 <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                                 <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                                 <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="for: ,      , end" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                       <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                          <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv6">
                                             <xsl:value-of select="sum(current-group()/RESULT_VALUE)" xdofo:field-name="sum(current-group()/RESULT_VALUE)"/>
                                          </xsl:variable>
                                          <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv6, '0.00')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                              </xsl:for-each-group>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                       <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv7">
                                          <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'TOT_EAR')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX, 'TOT_EAR')"/>
                                       </xsl:variable>
                                       <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv7, '0.00')"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                       <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv8">
                                          <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'TOT_V_DED')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX,'TOT_V_DED')"/>
                                       </xsl:variable>
                                       <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv8, '0.00')"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                       <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv9">
                                          <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'TOT_IV_DED')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX,'TOT_IV_DED')"/>
                                       </xsl:variable>
                                       <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv9, '0.00')"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                    <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"><xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv10"><xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'TOT_NET')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX,'TOT_NET')"/><xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_EAR',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_EAR', 0)"/><xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_V_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_V_DED', 0)"/><xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_IV_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_IV_DED', 0)"/><xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT', 0)"/></xsl:variable><xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv10, '0.00')"/> </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                        </fo:table-body>
                     </fo:table>
                  </xdofo:horizontal-break-table>
               </fo:block>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_CNT',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_CNT', 0)"/>
               <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_EAR',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_EAR', 0)"/>
               <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_V_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_V_DED', 0)"/>
               <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_IV_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_IV_DED', 0)"/>
               <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT', 0)"/>
               <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_NET',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_NET', 0)"/>
               <fo:block padding-bottom="0.25pt" text-align="start" orphans="2" widows="2" padding-top="0.25pt" end-indent="5.4pt" linefeed-treatment="preserve">
                  <fo:table start-indent="0.0pt" style-id="ts15" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 4" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="37.05pt"/>
                     <fo:table-column column-width="93.25pt"/>
                     <fo:table-column column-width="93.25pt"/>
                     <fo:table-column column-width="93.25pt"/>
                     <fo:table-column column-width="93.25pt"/>
                     <fo:table-header>
                        <fo:table-row keep-with-next="always">
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="234.65pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd">
                              <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Payment Method</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="234.65pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd">
                              <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Total Earnings</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="234.65pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd">
                              <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Total Voluntary Deductions</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="234.65pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd">
                              <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Involuntary Deductions</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="234.65pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#e7f3fd">
                              <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri" font-weight="bold">Net Payment</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-header>
                     <fo:table-body>
                        <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                        <xsl:variable name="_XDOFOTOTAL" select="count(.//G_EMP_DETAILS_GROUP)"/>
                        <xsl:for-each-group select=".//G_EMP_DETAILS_GROUP" group-by="./PAYMENT_METHOD" xdofo:ctx="3">
                           <xsl:variable name="PAYM" select=".//PAYMENT_METHOD"/>
                           <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                           <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                           <fo:table-row xdofo:repeat="R">
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="F , Payment Method" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0.0pt">
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_EAR',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_EAR', 0)"/>
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_V_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_V_DED', 0)"/>
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_IV_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_IV_DED', 0)"/>
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT', 0)"/>
                                    <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" color="#000080"/>
                                    <fo:inline xml:space="preserve" height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt"> <xsl:value-of select=".//PAYMENT_METHOD" xdofo:field-name="PAYMENT_METHOD"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                    <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"><xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv11"><xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Earnings'])" xdofo:ctx="17"><xsl:value-of select="sum(current-group()[.//PAYMENT_METHOD=$PAYM]/RESULT_VALUE)" xdofo:field-name="sum(current-group()[PAYMENT_METHOD=$PAYM]/RESULT_VALUE)"/><xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_EAR',xdoxslt:get_variable($_XDOCTX,'RTOT_EAR') + (sum(current-group()[.//PAYMENT_METHOD=$PAYM]/RESULT_VALUE)))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_EAR',xdoxslt:get_variable($_XDOCTX, 'RTOT_EAR')+(sum(current-group()[PAYMENT_METHOD=$PAYM]/RESULT_VALUE)))"/></xsl:if></xsl:variable><xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv11, '0.00')"/> </fo:inline>
                                 </fo:block>
                                 <xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Earnings'])" xdofo:ctx="3">
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_EAR',xdoxslt:get_variable($_XDOCTX,'TOT_EAR') + (sum(current-group()[.//PAYMENT_METHOD=$PAYM]/RESULT_VALUE)))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_EAR',xdoxslt:get_variable($_XDOCTX, 'TOT_EAR')+(sum(current-group()[PAYMENT_METHOD=$PAYM]/RESULT_VALUE)))"/>
                                 </xsl:if>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     , RESULT_VALUE" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                       <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv12">
                                          <xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Voluntary Deductions'])" xdofo:ctx="17">
                                             <xsl:value-of select="sum(current-group()[.//PAYMENT_METHOD=$PAYM][.//CLASSIFICATION_NAME='Voluntary Deductions']/RESULT_VALUE)" xdofo:field-name="sum(current-group()[PAYMENT_METHOD=$PAYM][CLASSIFICATION_NAME='Voluntary Deductions']/RESULT_VALUE)"/>
                                             <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_V_DED',(sum(current-group()[.//CLASSIFICATION_NAME='Voluntary Deductions'][.//PAYMENT_METHOD=$PAYM]/RESULT_VALUE)))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_V_DED',(sum(current-group()[CLASSIFICATION_NAME='Voluntary Deductions'][PAYMENT_METHOD=$PAYM]/RESULT_VALUE)))"/>
                                          </xsl:if>
                                       </xsl:variable>
                                       <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv12, '0.00')"/>
                                    </fo:inline>
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_V_DED',xdoxslt:get_variable($_XDOCTX,'TOT_V_DED') + xdoxslt:get_variable($_XDOCTX,'RTOT_V_DED'))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_V_DED',xdoxslt:get_variable($_XDOCTX, 'TOT_V_DED')+xdoxslt:get_variable($_XDOCTX, 'RTOT_V_DED'))"/>
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"/>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                       <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv13">
                                          <xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Involuntary Deductions'])" xdofo:ctx="17">
                                             <xsl:value-of select="sum(current-group()[.//PAYMENT_METHOD=$PAYM]/RESULT_VALUE)" xdofo:field-name="sum(current-group()[PAYMENT_METHOD=$PAYM]/RESULT_VALUE)"/>
                                             <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_IV_DED',xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED') + sum(current-group()[.//PAYMENT_METHOD=$PAYM]/RESULT_VALUE))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_IV_DED', xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED') + sum(current-group()[PAYMENT_METHOD=$PAYM]/RESULT_VALUE))"/>
                                          </xsl:if>
                                       </xsl:variable>
                                       <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv13, '0.00')"/>
                                    </fo:inline>
                                 </fo:block>
                                 <xsl:if test="count(current-group()[.//CLASSIFICATION_NAME='Involuntary Deductions'])" xdofo:ctx="3">
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_IV_DED',xdoxslt:get_variable($_XDOCTX,'TOT_IV_DED') + xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED'))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_IV_DED', xdoxslt:get_variable($_XDOCTX,'TOT_IV_DED') +xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED'))"/>
                                 </xsl:if>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="140.4pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     , RESULT_VALUE, E" padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                       <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv14">
                                          <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT',xdoxslt:get_variable($_XDOCTX,'RTOT_EAR') - xdoxslt:get_variable($_XDOCTX,'RTOT_V_DED') - xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED'))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT', xdoxslt:get_variable($_XDOCTX,'RTOT_EAR') - xdoxslt:get_variable($_XDOCTX,'RTOT_V_DED') - xdoxslt:get_variable($_XDOCTX,'RTOT_IV_DED'))"/>
                                          <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'RTOT')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX,'RTOT')"/>
                                          <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_EAR',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_EAR', 0)"/>
                                          <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_V_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_V_DED', 0)"/>
                                       </xsl:variable>
                                       <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv14, '0.00')"/>
                                    </fo:inline>
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'TOT_NET',xdoxslt:get_variable($_XDOCTX,'TOT_NET') + xdoxslt:get_variable($_XDOCTX,'RTOT'))" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'TOT_NET', xdoxslt:get_variable($_XDOCTX, 'TOT_NET') +xdoxslt:get_variable($_XDOCTX, 'RTOT'))"/>
                                    <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri"/>
                                    <xsl:value-of select="xdoxslt:set_variable($_XDOCTX,'RTOT_IV_DED',0)" xdofo:field-name="xdoxslt:set_variable($_XDOCTX, 'RTOT_IV_DED', 0)"/>
                                    <fo:inline height="11.0pt" font-family="Calibri" white-space-collapse="false" font-size="11.0pt" color="#000080"/>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                        </xsl:for-each-group>
                        <fo:table-row>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block height="11.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                    <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv15">
                                       <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'TOT_EAR')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX, 'TOT_EAR')"/>
                                    </xsl:variable>
                                    <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv15, '0.00')"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                    <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv16">
                                       <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'TOT_V_DED')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX,'TOT_V_DED')"/>
                                    </xsl:variable>
                                    <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv16, '0.00')"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                    <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv17">
                                       <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'TOT_IV_DED')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX,'TOT_IV_DED')"/>
                                    </xsl:variable>
                                    <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv17, '0.00')"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="61.85pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block xdofo:xliff-note="     " padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="0.0pt" linefeed-treatment="preserve" start-indent="0.0pt" height="0pt">
                                 <fo:inline font-size="12.0pt" white-space-collapse="false" height="12.0pt" font-family="Calibri">
                                    <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv18">
                                       <xsl:value-of select="xdoxslt:get_variable($_XDOCTX,'TOT_NET')" xdofo:field-name="xdoxslt:get_variable($_XDOCTX,'TOT_NET')"/>
                                    </xsl:variable>
                                    <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv18, '0.00')"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt"/>
               <fo:block padding-bottom="0.0pt" text-align="start" orphans="2" widows="2" padding-top="0.0pt" end-indent="5.4pt" linefeed-treatment="preserve" start-indent="5.4pt" height="13.872pt" font-family="Calibri" font-size="12.0pt">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
