<?xml version = '1.0' encoding = 'utf-8'?>
<!-- $Header: TEMPLATE_XXSC_XXSC_AR_INVOICE_GFC_en.xsl 115.0 2016/05/23 09:25:39 xdouser noship $ -->
<!-- dbdrv: none -->

<!--Generated by Oracle BI Publisher 10.1.3.4.2-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="66.6pt" margin-right="66.6pt" page-height="792.0pt" page-width="612.0pt" margin-top="0.0pt" margin-bottom="0.0pt">
               <fo:region-before region-name="region-header" extent="72.0pt"/>
               <fo:region-body region-name="region-body" margin-top="72.0pt" margin-bottom="12.25pt"/>
               <fo:region-after region-name="region-footer" extent="12.25pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(612.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(792.0)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(12.25)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(0.0)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(0.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header">
               <fo:block padding-bottom="0.0pt" padding-top="0.0pt">
                  <fo:table start-indent="-66.6pt" style-id="ts17" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 2" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="580.25pt"/>
                     <fo:table-column column-width="29.05pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="42.25pt" number-columns-spanned="1">
                              <fo:block padding-bottom="0.0pt" padding-top="0.0pt">
                                 <fo:table start-indent="63.05pt" style-id="ts17" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
                                    <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                                    <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                                    <fo:table-column column-width="235.8pt"/>
                                    <fo:table-column column-width="270.6pt"/>
                                    <fo:table-body>
                                       <fo:table-row>
                                          <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="46.65pt" number-columns-spanned="1">
                                             <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="12.0pt"/>
                                             <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                                <fo:instream-foreign-object content-type="image/png" width="216.675pt" height="27.929998pt" xdofo:alt="An Image" xdofo:image-uid="be1f806f8f1df79100886c91f40a02ea">iVBORw0KGgoAAAANSUhEUgAAAtIAAABfCAYAAADF2yCFAAAAAXNSR0ICQMB9xQAA
AARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnMAABJzAYwiuQcAAAAZdEVYdFNvZnR3
YXJlAE1pY3Jvc29mdCBPZmZpY2V/7TVxAAActUlEQVR4Xu2dX4wkR33HL4kTBZRI
2MkDRIocg+RgiORg++RLzqfN/dvbP/bd7f/Zm52dufHs3Nx4NPZk5LTRStl1FPD6
AWOkxAYJjJEig6wYiBQMD+D4BQcJ4rzEJlKEw0MwD4nNQ7AtJYTL7zu3fcz1/bqn
a/pfdc/34XOY3e3q6qru6k9V/6rqwMMPP5xLHux1/mT56O2XwrC9vf17WhqEEJI1
0kb93NtmafS77aPa8Vlwbu7ID7Q8erlYXX/4wIEDv6SlQYiNtKrrf75y7Pb/0+7n
c7NH/n1lZeVXtONI9kgd/Y+3zly6zeq9zz777C9rxwXRbdY3l4/e8b9ammDm5pt/
TT0wD1CkCSFFQNooijQhlkCRzi9SRxRpEyjShJAiIG0URZoQS6BI5xepI4q0CRRp
QkgRkDaKIk2IJVCk84vUEUXaBIo0IaQISBtFkSbEEijS+UXqiCJtAkWaEFIEpI2i
SBNiCRTp/CJ1RJE2gSJNCCkC0kZRpAmxBIp0fpE6okibQJEmhBQBaaMo0oRYAkU6
v0gdUaRNoEgTQoqAtFEUaUIsgSKdX6SOKNImUKQJIUVA2iiKNCGWQJHOL1JHFGkT
KNKEkCIgbRRFmhBLoEjnF6kjirQJFGlCSBGQNooiTYglUKTzi9QRRdoEijQhpAhI
G0WRJsQSKNL5ReqIIm0CRZoQUgSkjaJIE2IJFOn8InVEkTaBIk0IKQLSRlGkCbEE
inR+kTqiSJtAkSaEFAFpoyjShFgCRTq/SB1RpE2gSBNCioC0URRpQiyBIp1fpI4o
0iZQpAmZbLb7/Q9qPzchjjSiIm0URZoQS6BI5xepI4q0CRRpQiaTVmX1sbWTd/4E
z3Z5fur7vU5rVvu7IHqteq08d+Q1pFE6dfjH7Vqlp/1dGkgeKNKEWAJFOr9IHVGk
TaBIEzJZ7O7uvqe6OP2C9oy3a+d2wwobRFxL4961u7/oOM67tGOSRM5NkSbEEiZF
pPf29n7d6XensmjzkkLqiCJtAkWakMkBjf7m2RMvac+3S3tz7ZFR0tbcWHpCO9al
vjL3lbTFT85LkSbEEiZBpLvtxpmV4wd/imuS/32nXav86TiSaRtyPRRpEyjShEwO
jdI9z2jPthd5QSxox4N2vfKA/M1IaU1b/uScFGlCLKHoIg2JFjH8mffaGucWP5P3
a5ProEibQJEmZDLAhEB5jkPJJmKmNXHDiHZp+tCb2jFeMEKzs7NzvTeNpJBzUqQJ
sYQii7S0azeuHL/jv7VrA+165b48j0zLNVCkTaBIEzIZIP5Ze679cPr9W7xp9Lrt
GfldKGEFvWZj3ZtGUsj5KNKEWEKRRXoghceuHY122Vw4+eLMzMx12rF5QK6BIm0C
RZqQyWD/WQ8lm1iBQ5s8s+s47105fvBt7RgNSeMmbxpJIeejSBNiCUUWacfp3yrX
4SuF7crqo3m+PrkGirQJFGlCJofK6WMva8+2lyBxa64vPKUd4wWrd6Qpf3JOijQh
llD0GOmt0tnPatd3bvauHzqO89vaMXlBroMibQJFmpDJAc/w+qnDr2vPt0tteebr
QdIWZuUPxFinGR8N5LwUaUIsoegijXawcvrod+V6rrQ7kOh+v3t73p9VuRaKtAkU
aUImC8fp/6GfTFcXTv5DGAHGWtR+Mg2JTjOkw0XOTZEmxBKKLtIAMt0sL/1VafrQ
G43S2ael7fwt7e/yhtQRRdoEijQhkwdinb1hHmHWjx5m8BLxhHlg/ei0R6Jd5PwU
aUIsYRJEuqhIHVGkTaBIEzK5YHS606i1INba78OAdgFpYHk97fdpIW0URZoQS6BI
5xepI4q0CRRpQkgRkDaKIk2IJVCk84vUEUXaBIo0IaQISBtFkSbEEijS+UXqiCJt
AkWaEFIEpI2iSBNiCRTp/CJ1RJE2gSJNCCkC0kZRpAmxBIp0fpE6okibMOkijU0j
sOTXKHqtek07Pm2wUgLqDGCCF7Z9voZ6+SH8PuvJX3kEZYayw1bYWtmizN3y144v
ApiAWF2cfkF7DobBfWaT3EkbRZGeIDBBttdtnsFzifbZfS6B0+8eKnJ5XdhY+YTf
M9pt1s5fsuDaiyrSeAfL/TXVrpV32vXKA2hPrrr3lB1h84bUEUXaBFS8dlEaRRRp
PNDatXpBY60dnzR4aAdSt7n2yOaZE/+o5S2ItZN3/gSNK/KPutbOMclAnCHH6FBh
W2ytDIMoYtnutwkjpXSrdPbzFOloUKTDs+1074S8nF+efT7Ms4q2T57rL0Esdxzn
fVqaeWVz4eS35BrV+721WfqLcUQnbooi0nLv/H6nXr2/UbrnmY35qVcl/yPbmdrS
zDfatUpvp9+/JY/PrVwDRdoEirSdIo2yhqisHD/4jpafccH14lomOUwHm4lgJCFs
3YcFL+6t8tKTeS9binR6UKRH02vVq2G3tg9i4/TRf243qheLMGJIkU6efr87dX55
/jnJb6h2xQ/sdtiqrD666zi/o53HRiTfFGkTKNJ2iTTqA5taaHmIG2wFjU+gWj6K
CEIWkuicaKBse53mWS0ftkORTg+KtM7gS5wIdHnuyGtaeUQBHd6Lm6t7eR6lpkgn
R7fTOrW5MO1bvlForJ35gryHbrP9WZa8UqRNoEjbIdIYJYWYaOdOGpw3yoYctoNr
y6psEY6Tt1h1inR6UKSvBQLtt4V9nKBD3aqVP5rHcqVIxw9Chyqnj31P8he7QHuB
UNu8nbjkkSJtAkU6e5HGqPA48blxglEaTB7T8pdnEP+Ma9OuOU0Q445RNi2PtkGR
Tg+K9C9Ah7e6PPu8XG/iIjNM5cyJ72x3ux/S8mQrFOn4QLt8cXP1Y355TQq883ud
5vylS5ese64lfxRpEyjS2Yo05FU7X1YgrCQvwhcE7tVxJmcmCe41PG9afm2CIp0e
FOnL9NvNtdL0oTe1a/cDIjK8WoXLOB1nHPNgp3UsL2VMkY4Hx+nfWp6f+hfJk1Hn
DZ0v7323H4ZklA5oV8t9G+prGMkXRdoEinR2Io00tXNlDSbl5DnUA7HQNoxCa+Bz
su2x0xTp9KBIYzCh4sg1hqo7EcgXMWFwZ2fnei0tF7QBWGkBK3zIcaHSxrPZaTcW
81DOFOnoIBa6dPLQf2n581Kem/pXlOt2v/uhoPtD7ssb0Slsbiw9IR3DN7S0NNqV
1UdtCnWRPFGkTaBIZyPStkq0C8oFLyMt7zaDpQLTmEwYFYScaPm3AYp0ekyySOPL
V2N94Sm5vpH1dmFj5fFxJwfivbUvNqFGvOWFf872sqZIR6PTqDaXj93xMy1vw2AZ
u3EnB+L+xnnK81OvSFoj7/HGucXP2CLTkh+KtAkU6fRF2rZwDj/w6TRPI9OQU+06
bCWJrxxxQJFOj0kW6YbIrVxbYJ1hHWjHcW7SjjcFbVltZfZrkm7gOdERd/rt27Q0
bIEiPT69VmN1lEQjdOPBXutYXBvbQCKlIzdy9Ltdr9xnQ91JXijSJlCk0xVprOAQ
dcQU8VhYXg15cncxdMEOX/g5fh9HeAPOpV2HbSBcQst/FLwxmEnEXGM9a+16soQi
nR6TKtIIu5Dr8q0vtJHYSCWJa8aqIKNGp/Fe2N11btCOtwGK9HhgZQ65t36q5cml
WV7+1N7e3ru146Mw6Mgtz/y9nCPwvpf26a6sd6aUvFCkTaBIpyvSEDIt/VGU56e+
D0k2nQiIFUEgPFHk3daRU5c4Oidg0DkRsR21XB0aRNQFJmbGcV6bxA5QpNNjEkW6
3+2c8hMsgLYu6VU08C4bVfbnl+e+aoOQalCkzUG7XTp5539q+QEYeOp26ktJr6Ih
7eZng+5/DOA0m83f0I5NC8kHRdoEinR6Ig350tIOYrCxR7c9o6VnwuXd/MoPjTtK
jftESzdrcF1h61ADInyhsvrJcUNYBuUq90aU0X8cG9fn6zigSKfHpIk0BgLKc4OY
UfU6G6WzT++ltPNgGJnut5tzNpY7RdqcIIFFKIe0wR9Iq65HyXTWkw8lDxRpEyjS
6Yk0eppa2hoQvDgE2guE8d61u7+onTMIrOShpZc1447wgygC7cUVau08YcAonC1b
F1Ok02PSRLpdK+/I9aj1BIlO+5M23mlrAasr4LlM4jN/VCjSZjj97pRInBoXjRU5
shgBbqzd/Td+5YP3v9Pt/kFWz7zkgSJtAkU6HZGGFGvpagxGKBPeuhsT80zDEmxb
tm3cyYUo36RG2KNsrhNHZy0OKNLpMWki3WnWLki787b3+tBR39trZiKsWK4scHSw
VunZVvYUaTMQG12aPvwf3nxcftf2P5xF/WLwpTx75N8kH2o9nl+e/busRqXl/BRp
EyjS6Yi0yShwWsIK6TMJSUCYiZZOFuAT8TjCigmDcY1C+4EGsro4/YJ2/iDQsRl3
ia84oUinx6SJNEC7s795xeDa0AZt9/vv1/42LbZKC5+TvKj3D0albRDTYSjS5qDd
ry6c/Kac/0q5pRETHYS0RRgp95VLp9v9Xe24pJFzU6RNoEgnL9KQvrCjv1vlpSe1
NJICLzWTkWlb1pYeJ4wCEm06WXNccJ79zSDUvPiRdv1rUKTTYxJFGqCzeX5l/sty
bT+3YRMUSNby8YNvecvdxbZdDynS44N8LUu+sDqHDeVUX5n7W79yaktdZlFOcm6K
tAkU6eRF2iSsI4syNgmRwMi6lkaa4KVnGpaCUSW8vLX0kgLn25ifelXLTxD9fvcj
WnppQZFOj0kVaRfpyE/Zcl3NjdXHpKzVewjrWdsgXS4U6Wgg1MOWOSmO079VykQV
THx17d58869qxyWJnJsibQJFOnmRDiuqWE5NOz4NEKOo5ckLHmzt+DTBJEEtb34g
z1nduzjv+qnDr2v58gOdlSzlgiKdHpMu0jYRNCqNjntWMdwaFOliUTl99LtSLmp9
9jqNE2mHn8h5KdImUKSTF+n25tojWppestycw2RDk6RjjEdhGhvdazVKWjppgfNr
+fIDL+0sR0so0ulBkbaL2tKM786HNoV3UKSLxUAyfXZbzCK8Q85LkTaBIp28SEM4
tDS9JLHcXVgQ0xt24mGWq3eY3K8AI+02vPw2z554ScufH71mY11LJw0o0ulBkbaL
oB0XUQdZ7zjnQpEuFjs7OzdKuaiSKXX94szMzHXacUkh56VIm0CRTl6kw24tnXX5
YlUOLV9eopRFVDAZT8uTH5hMqaWTNpikKfkJJXogy/AOinR6UKTtYvCc+sgfhMYG
QQUU6eIhZaIuhTf4Qtls/qZ2TFLIeSnSJlCkkxfpsOfIunzDxh5nGcttEtaBzVq0
NLKifnmVAjWvXrIM76BIpwdF2j5K03/8I60O0PZQpMNDkTYjaIOWtDdnkXNSpE0w
EWmMrEJOikTY1R/SEOmsyzdsPlFm2vFJE3Zk3wWTPLX6yArTWGmEpWjlkDQmE0+1
47NCy6NGVuWqEbb9oUinR+XM8W9LmauSaov8UaSLR7u69pd+X0PSnnAo56RIm2Ai
0pNMFJHGC1NLkySLbV9Q9tcTv2ZXN0JGQZFOj6AJh9vb2W4c40KRLh7tWvnP/CYc
jiuv4yLnpEibQJEORxSRDjvZkMQHRq+1usgakx0uCXGhSKdH0C6HtqzcQZEuHgPR
tGTlDjknRdoEinQ4oog0lrXT0iTJgSUHtbrIGpPNbwhxybtIn1+ef84b1mIrQfMw
bAkLKk0felPLH4CkasekTVCoIEKapDPwonbcpIJNw6Rs1M7Rudm7fphmeck51XwA
irQCRTocUUQaIQZhl5Yj8ZDlmtxB7K/X7dtIEaKRZ5FG++cX+0kIyRcUaQWKdDii
iDTAskqU6fTIehMWP7Acn+SPIk2MyLNI91r1qlwD73lCCgBFWoEiHY6oIg0o0+mB
+1qrg6wZjM5RKogheRbpxvrCU3INvOcJKQAUaQWKdDjiEGlAmU4H21bsGEbyR6kg
RuRZpDfuOfZP2jURQvIHRVqBIh2OuEQaUKaTB2WslX3W7DrOeyV/FGliRJ5Fevn4
wbe0ayKE5A+KtEKvVa9pF0WuJk6RBpTpZOl12zNauWcN6l3yR5EmRuRVpLf7/Q9y
oiEhxYEirYBlwrSL0ijizoZhQYdDK78oQKq0c2WJVu8aWKpHOz4pTHc1TKK+4gCC
L/kLLdI27cJHsqPbrJ3Po0g7/e5U0FrC2rUSQuyl12nOjyPSvU57urpw6ptamuBT
MzPXqQfmgfrK3Fe0Rk5DO54Uh/3RUrXuvWD1CS2NJDEZwY/7C0JcmH4B2tnZuV5L
h5A8ECTSW+XFT1/KabgKISR+rvzH7u7ue4Z/YTP7Wxa/ozVyXjACqaVBioOJ5OHe
0dJIEvRatbxoYAdBLY2s2SovPanlVwMjdnmNiyUEBK0hXVua+cazzx4wHtkihBST
wT+QaLzsvb+0Fay1qzVwGhi51tIgxSGs5CHcQDs+aUzCkNBBzEL2R7F+6vDrWn41
0BmgSJM8g2dQ7mVVpDE4Q5EmhLgM/tnfbMHaz8peTMI6bL8mrD4SNdwAHSGkY/PS
aUmBF17Y0Imt0tnPa2kkzf6ugGqeNGzblGV/hZzQ8dG27s5IiAlrJw+9od3faG8o
0oQQl8E/wyO8eGl6/8gmTJe9s/V6IL37e9QP8olJaeOE1yCsYVgkL1RWP6n9XVGB
tLnXPoqsBG9/MxM1Txq2hXeYhHWAfrd9VEuHkDxRnpt6Rbu/wXa3+yHtGELI5DH4
Z/jTc+nU4R9jzVjvH9oCPs8PN2hB2PqZ3G8JOcSWmowq+0kkRMzG606C4c7IKLIc
sUfdannSwH1ry9cFtAWSn7e1fGog747jvEtLi5A8cV+19HG5p9UvMXEv64fJjRvz
U682SmeflufnJu1v8gbeQRc2Vj5ROX3s5Xat0rt06dLI8sIxFzdXP4aykGMfl///
bu3vCLGJwT/eUAnIqo2TD01GH0FteebrWjpZAkEKCkWAcIUp+1ET7LIKY0gTk/sh
63sBIUZavvywJbYfnTItf37gvmN8NCkCQSt3xBknLW15VdK8Iux4P3Tbzbk8P0d4
h1XOHP/28HVhkqb8/Abt7wHejfu7SV45pnLmxHeCjiHEBgb/aKO8tsk0FsjHaJc3
n0EgNlVLKyvQ2w6zrvAoiQpbFpBt7fgigEbX5H7I+l7YH9k1u38z3pzFNDYa9Pvd
j2hpEZJHStOHf6Td5yCO8A7IurY6CNqKPIePnF+ee06u45q2Q37+VW0tX7wbK6eP
fk87BqP046z/S0haDP7xe8HbItOQJpNP4wB519LKkna9/JCWV40g8Qu7nBrqFQ2U
lkbewQizds0aCFeyoRwwWqvlzw+MemX1/OG8+Lyq5csP3JccjSZForG+8JTc22pn
8rIURhuVDhJ1jMbmUSD77eZa0K6QvXZj0dtOIJzDb/QfOP32h9m2EFsZOREKL/Oo
q0pEYRyJBraNRgOTXe78JpxhZFP7ez9sWwEiDkyFFHMAtHTSxmTjGBd0CNPuBAy+
nJw98ZKWnyC67caClh4heaXf7ZwKErxep3VsXMELsw353l4zdzHCW+XFv5a8q50P
gA1tvB0EbxiIl0692g4TY01IFrhb/6o3rwtGNjGaqiWQJBAPjCZqeQrCxtFoYLIx
h1+MM0YKTUIE4ggPgLyjQ6P9Lm1MJRrxhjZNnjW5B1ww+p6mTNdX5r+s5SMIdHY5
YkSKSG1p9mtyj6uSh3dNlFHp/Zjga9IFcYx4ZwE6H0EdhL4S/92uVe4PHJF2uh8Y
/ntCbOJAp1FraTeuBiQgLSnxW9kiDDhWSzNrTDaSCfoKEHYd7bhCGpAG6gKdqbRH
R11wXtOJbwD3t5ZeVuDeNOkIuUCmkw7zQPoma7QP0+u0ZrU0Cck7gy9JAZIXZQWP
bad75/KJg29500R7u93vv187Jg9slc5+Tq7jms6HX7wz2vfNhZPf0o5pVVYfZYw0
sZkDWHfYe+MGAQnAMUkKNeRnXInGmrdamrYQRgZHhSKg7EeFu6Ce4lxD2x1JRahP
2mtz40Vmssydi61fJkxi5YdBxyipMKtxyxjY/swREpXzy/Pq5DmXdqN6cVyZxqod
0l5fWWISz3mUkBGXLAeUIMa1pZmrRvLl3fcl+blvqAo68tpKH0HHEGIDRpO2hrki
1DGOkuHBN4kj9gIRwAOspW0LyB8ET8s/CLtMG4QqqLMR94od3uXbMHKZtFDj3sJ5
xxnBBVm+SEYxTogHQFmgTOJ67qKW8WAOBdeNJgUHbcmoeOaOMokuLFi94/zy7PPo
lO44zvu0vzGhU6/ejzC4rEdyW9X1HVxXr9lYD1M2eD+2ahWnujj9QqtW/ujeHtsW
Yj9G2237ASnAmr6mcbT4e8gYQh7GFQsXiAAmb2jnsQ00FtrItOmuhLhe7ygi5DqJ
iZb7S6FdlV+Ajk/c53PlbtyvEsCWCYZ+4N6Pcn04NsqXoTjKGM+c02//kZY+IUVD
3nGO3Pe+o9KDTm6Ekek4wLtlq7QwCKvoNGr1LPNCyKRw+RPMmKPSGhA7SAxe0hgV
hYANg8lv+F3QqOw45HHNZJQFhBojB+N+socQIRQGdYhyTWpSIO6ToFFL1DtGUyDV
+FstjSBwHehQIY0ocgfCjupnjUnMfBCDukdHdkRHEtKN5wSd53FHoIfJYgIyIVlS
X73nGbn3fWUaIA54L4OvNHi+Nxemr8QZSyf3Nu3vCCHxMvgnbplOG8ZopoNJ5wcj
1RD7ASJc3g6V+zuMqsbZqcKXjXFEPisgttp1RAExligHlyjhUn6g7rTrIaTIoG2p
nDmJOF71uXBBm5bm5kQYLZfO8ZU4awxGcIIeIelw5T/yKtN+y8SR+IH0anVgC3h5
YWRby7vNJCHTSUKJJpMMvvpJZ9V3I5VhsIRdkkKNVT825qde8Z53c+HkixRpQtLh
qv8DmbZdloYxjSkm0UDYhlYPNoBVTJIKa0mDvMg0JZqQy5MPz80d+YH2jGhAqLFh
0c7OzvVaeiYghAuTCSunj72snQtgSb5LjI8mJBXUHyJ2M2qcatLwhZ4+GO3V6iJr
EPObx5FoLzY/d4OJVPXKA1q+CZlE0OZsLv4iJjks2Pobotvvto+GmSwMcb4cDlfe
Cbtt/4MxLJ9HCAmH+kOARgKxx9pDmiWDNTZzOLGwKMQ9STQKRZQ7vFhtC7G6vMSd
vUsJEpIlzcrqY/KcGMm0BtrW4bkN8rOx09zddW7Q8koIiR/1h8OgN4zR3zhm+UcF
8dBFGHnMM6gDrW7SBqEcSW1OYgNYicWGZw7hU3mavElIFvTbzbX1U4df156hNMEX
rayX4CNk0lB/qIH40zjWnB6HwSh0tz2j5YukC+ohS8EbvCikYzcJHSp0YrN65jA6
xmeOkPCgw4nwi9L0oTe1ZyppsHPgbgybuRBCzFB/GAQ+8ab1ch9s9tGq1zgiZhcI
P8BIZZpCPUkC7QVCjS8BaZQ3PilToAkZH7RR91VLH5fn9cpydEmCmOtepzXLUWhC
skH9YRgGIR/1ygP7sVzqAz4uUTYoIekBocY9kGTc9GA9ajnHJAq0l0F5b649grAW
razGBYKOjYEYB01IfOB5xeoa2CJbnrPIMdTD4JndKi9+2un3b9HOTQhJD/WHpkBy
BrvSiQB7t6weBRoEyDhGGzESRmHKJwj9gfBiolwU0UMYD+4j3E+8F/xBeSOOGgKM
MtPKMgh3wxx2WAlJHnxV7XWbZ5obS0+U5468pj2To8DI84WNlcfjWkaPEBIP6g/j
AL1xLNmDtYfxwnZBqIa7ux1HwIoLXhyDJZtErofr3wtk0L0fKM7jg2fJLUetnIef
O4ZKEZI9Vz+z5Z1rntt6+SEskYffOxlsOU4ICcPDB/4fd0Nt/KnTujoAAAAASUVO
RK5CYII=</fo:instream-foreign-object>
                                             </fo:block>
                                          </fo:table-cell>
                                          <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="46.65pt" number-columns-spanned="1">
                                             <fo:block height="12.0pt"/>
                                          </fo:table-cell>
                                       </fo:table-row>
                                       <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                                       <xsl:variable name="_XDOFOTOTAL" select="count(.//G_AR_INV_DETAILS_GROUP)"/>
                                       <xsl:for-each select=".//G_AR_INV_DETAILS_GROUP" xdofo:ctx="3">
                                          <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                                          <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                                          <fo:table-row xdofo:repeat="R">
                                             <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="46.65pt" number-columns-spanned="1">
                                                <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                                   <fo:instream-foreign-object content-type="image/png" width="216.375pt" height="21.3pt" xdofo:alt="An Image" xdofo:image-uid="f17f965d1f1ef12f08915a8e581ba504">iVBORw0KGgoAAAANSUhEUgAAAtEAAABHCAYAAADBaRtwAAAAAXNSR0ICQMB9xQAA
AARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnMAABJzAYwiuQcAAAAZdEVYdFNvZnR3
YXJlAE1pY3Jvc29mdCBPZmZpY2V/7TVxAAAeiUlEQVR4Xu2dTZAkR3XHZSNHGHMB
BBEYHCGMwnweBNJG7GpX2vXsrNiZ2Z2Pnd6ZntFMb/fO9raajo0yow6igYnQjHAA
64Mt+WCEIyxjDhisQKCDED5gWwcwHABzQIEjjDERfB2M5AOyfPDH+P17ptje5nXW
q66srMzqd/jxMduZ+Soru+pX2Vkvb3nkkUec0ut23/2B7Wu/32qsf7B1aW2vWat+
fG3+/n/g2Fye+yI+A9rNRhvluDoVRVEUJUR63ehUq76+G9/rer3eK7nPKYoNyMHu
3O60FuMxV68u/uX6wnv/nnMwcGl14a+u1qqPwNm6UWeKxudvc/VOKuwfbUId/oZO
c6tRu3j+s4vT9/zs3H137Welcvbk9zYWZ76Mk7rT7b6da9cVOLb44jfMdru1xJXx
gf6DDBMzwIMOVyYLrttzRXur9n7umIqCizEEdnZ23swdT9Hs7u6+hotXCq4BXL3D
5HWt6LS26lx7ANeuW2655de4cj4yKJom6J7zu1x5X1mZPf2twftbe6uxFdJ56X93
R5ybkMbY3t7eq5u16sPccQyzG9AYo1jf1mk1HtxcPveFhaljLw6OtXGZP3Xkv0iw
n7u8Xnls+1r79P7+fi7nmK6/t0vPiSsoptsGY7wpYFvgS7W1fvFRyC53AmyDdnBw
RQg1ntS4mAA94X2KK+MD6C8uZoALH1cmC67bc8Xy/Sf+jTumogjp5jsIHrIo/v8b
Pp6iySpkmOWhehKPC7M9eZw7zDBx7cVghimUMUPx/u9w/By4qYdyTL1edPT80HGt
zE3905NPPvnr3Od9BDPpFPfIc4MxFsLxwFso3v8Zjp+j22lN+zzGMNt8aXXpiaUz
x3/KxW8bTJDiGnat1Vy2ea67UYfG1t3/zbVZFFEU/d7guf+VoLOAGUWII9ewK3AB
2u50Zrj48kAlWoZKtBtCkYdhVKKLkWjQrK9/KIRxQ7GWTqJrlfnPUMy/Mj6iqHM8
lGNIkmhAY+zDec1W2qIMEh2122cfWJr9EsVY2LV0+cyJH3a26p3r16//FhdjGiZG
oiHPWL/MNVgUWO7hYpmASrQMlWg3hHLjHUYlujiJBu1m47LvY4fiLJVEY6nj/Kkj
/8kdw8aFuaeffPKWIGajJRINfF+mEqpEk6z+Jt1DL1VmTj5PsXlzDcXs9Ha7dS7L
w1PpJRqDzjd5HgZrVrnYbaESLUMl2g0hyAOHSnSxEg18F2mKsVQSffmBi39C8bJj
A2tOe1H0Rq6cb0glGvgs0iFKNPp+cfr4j7kYfSBqN8+rRI8AL8IsTB39D64RKdXz
01+HhPZfEiTJGgRrqvFvAEs0uPISVKJ5XEut6/ZcoRJtB5Xo4iUa4rbdbs9y9fgA
xVgaicbs4fzUsRe4+GOubK5epy+099/nNBKNMdZtteZ8PD8hSTTGT3Nz9aPD6+l9
g4Tz9Vz8Ukop0Th5jbXK41zlJvDlwaw1pHbcFwBxo0VGDmT6kMpL3ks6VKJlTKJE
45hdw8UYAirRxUs06EtO1Jni6ioaiq80Eo1sCRSrcVzg5/Dr11uZ15XmTRqJBhhj
H/DwHIUi0XgZtXL21HcpDu+ul4OszE19Z2Zm5lbuGKSUTqIhv2lmhfFlwYxytxsd
4+rLCuqF0I+aEcffuXI2UYmW4bo9V5gkmvu8wqMS7YdEA1w3u1H0Hq6+IqHYSiPR
w2ntRtFu1t/n+7GklWiAMdbrdO7y6dh8l+hQZp9jaqsLn15ZWXkFdyxSSiXRyHgB
KeYqHSaWZ7w4wdWVB1G7uTYstFgmwn3WJirRMlSiFRMq0f5INOhLTsZjtw3FVQqJ
hnRKRSiEdHfjSDQ4GGPRHVydReC7RNerC39hQ6DR7w8szvwtsvLgVydce/f3+WNB
jmn8O0Au8I2l2WelafM6W/UrWcduaSQaHSgR6CLkeRis1Y7zU7v4eVslWoZKtGIi
jURfazXX4wt73mD2h4tXSqgSDTC2fRJpiqkUEr1x4dxTFKf4gTGEhwKKcyy5wxjb
2em+havXNT5LdFaBRto5pBnEL0w24sYmKFGnVa1Vzj01Ki5q60jWttJI9Pa15hnu
Gm4buifctKPoTQFzYE0xnly4oAeBuBa9e+AgWHud1zKSQVSiZahEKyZwcaI+E4mF
bzOkJkKWaICZ0Ky7NtqC4gleog9FLZUM+Z7uLotEA6yd3dvbey1Xt0t8legsAk1+
8tx2q7mcZ45u7PTYbtZba+env0Zt9q91cMa3vvWtv8F9Pg1pJDqy0N44sH+MwaCS
bNUNWcw6YxMqKtEyVKIVEyrRfko08EWkKZbgJdqU1s7ETteP2VqOrBINfBBpHyV6
XIHGco1et+t8zTmkd23+vX+HpbRZXyoEQUs0lmSYBAFg+UbIAmQDlWgZKtGKCZVo
fyUa4DpH/X7Tz5iuoTiClmhMNM2f5DdXSeLyeuUxX9Pd2ZBoAPGjPiosG4lvEj2O
QMPJsGyj6HX08Efu72kJVqLxZUcOZy7QGJwsFzsC+o5KtAyVaMWESrTfEg36u8AW
KNIUQ9AS3dmq/wHFl3oWGuDncV/T3dmSaFCkSPsk0XRPvHTu5N2iWGKq505/g5zs
XT6O/XEJVqKxnpgLMgYCjWwdXNlJQyVahkq0YkIl2n+JBkWKNLUftERL09qNwtd0
dzYlGuC7UMRMqi8SjVncxel7Uu1CaCOdnI8EKdE4gUkvEiKd3HC5SUUlWoZKtGJC
JToMiQZ5xZoEtR2sREM0s2RXAL6mu7Mt0aAIkfZFotMu48CLp2UUaBCkRCftRpj3
NtqhoRItQyVaMaESHY5Eg0Z1+ZOuRZXaDVai06a1G4WvDwgUm1WJBs3N1Y+4FGkf
JPqgL+XLOPovEPZ6r+LqKgPBSTTWOHPBxfgshUWhEi1DJVoxoRJdrETjOmYayxxX
a1W6g7gTOmozSInGr7vzp5JfKIQQ0X8bx4qP6e6kEk1j7DlJtq9BXL4kV7RE4120
ytn7xNt5l12gQXASbXqZsP8ioaU3LsuESrQMlWjFhEp0sRKN9nvd7jsWpo69yP37
KNqN2rYrYaX2gpRoSVo7vBSGjTDofyceYy+K3si1UxRSicYYwzHOnz72Avfvo2hv
NbZcZCYpWqKbterD0mUc8LEoin6Hq6dMBCXR2OmPCyxGl3HwqETLUIlWTKhEFy/R
aB8bVC2cOvIy95lRtJuNyy6kldoKTqIxu7g4ffwnXJyDYAtmxDw/dTRRMK9srl73
Kd1dGonGrDI+L5mZHwQbhuR9TouUaIyThamj/861xdFq1B7ycX28bYKS6NrF85/l
AgN4oQEnebCgcoBKtAyVaMWESrQfEo0yyLxEfxOdi5io3byQt+RQO8FJtDStXbyZ
imTtNJZE+JTuLq1Eo0z32rWz9DfR+QSYee22WnN5ntciJZrugeKUdtiYpuzLOGKC
kWgIMgYpFxjQdHajUYmWoRKtmFCJ9keiQae1Vae/i0Ua94/tdns2T8mhdoKTaEla
OyzliNc5S6UbSxx8OcZxJBpgjKXJQtEX6ahzIq/jLlKiaQx8leoVfd+6kf2lJL4S
jEQjZR0XFMA66eFCyg1UomWoRCsmVKL9kmjQqq/v0r+lEmmseR2swybURlASvd1p
LUokcXBd+aHIJZbxKd3duBIN0qwDBki/S2J1dx7ntyiJ3t3dvZ3qFIlimdPZcQQj
0ZA9LigA+RkupNxAJVqGSrRiQiXaP4kGl9cqn6B/F4t0X3IOlybYhuoPSqIlSzPw
4LHX6712sFz13Omv0b8l9rkvx5lFogH9/Qn6d/EYw3KWXi+6Y7ierBQl0fQQFUkf
JK41tzZ8eXhyQRASfbigfeTmKjvd7tu5gsoBKtEyVKIVEyrRfko02Fw+9wX6jFhy
8J3I4xxR3cFINO6bFEtivJfXK48NvyTYaTUepH9L7G9f0t1llWjwwOLMl+gzacfY
m7i6xqUoid5YnHmG6kw8djxw0TG/jqujrAQh0YcvkbBBVc6e/B5XSLmBSrQMlWjF
hEq0vxKNiRZpPTG4d+zu7r6Gq29cqN5gJFqS1q4vRUy6OvS3JKMHiF9ILBIbEo1j
Xpmb+iZ9TizSeMGOxthtXH3jUIRE9ycxT939C66NYZAXepKWcoAgJNq0Q2GzVv04
V0i5gUq0DJVoxYRKtL8SDfb29l69Mnf621zZUWDdrk2RpjqDkGiI0fzJ5BRupplk
iYQDbibbNTYkGmCMLZ858X2u7Cjo/vsc9beVTCVFSHSvFx0lSRS12dmqX5mkpRwg
CIk2bbCCnKFcIeUGKtEyVKIVEyrRfks0gGRU7r/3B1z5UUCk6Xy9kqsvLVRfEBIt
zbBxzZD7+FDoEo8Xs9lFp7uzJdEAx70wdeznXPlRYIbWhkgXIdF07xOltpvEpRwg
CIk2rYfGkyFXSLmBSrQMlWjFhEq0/xINet3uu9Puani4PXFmkaa6gpDoytmTz3Nx
DSLJ9Sx5MRG43DWSw6ZEAxpjd5I0vsTVMQobIl2ERDc3Vz8qealw+cyJH87MzNzK
1VFmgpBoLhiAJx+ugHIzKtEyVKIVE2kkGr+e4Xtnm631i4/alpGySTTAuUq7q2Gt
cv5zWY+P6vFeorGJiESKsOtgUozSFHm4BhX5M79tiQZpN2MBaernKEKiN5fnPk/1
JV4f6Pr03KSthwZpJBp9NHg9twGWSyX1+0iJxheTK6DcDDqa6z+gEn2DSZRoyEae
lClzDo6H+kwk0XmB77Jt+SqjRIOo06pSuVTnK+sxUh3eS7R09lj6QuDymRP/ypUf
xrQ0JG/ykGjQTrkZC8gi0kVINF1zvkL1JY4XPISqRLuHzs9zSb8AjJRo3FC4AsrN
qETLmESJzhufx1daVKLDkmggXfs7CGZ2xj1OKu+1RB9KWGKMWHogTU0n7eODOouZ
jc5LokHazVjAlY3VPxqnL4qQ6Mr9J/6F6ks8v5fXKn9a1PktkqAlunbx/Ge5AsrN
qETLUIm2j0q0XVSi07d/tbb2MSqf6rw16+sfGqctKuu1RF8RZtRIM2vc6/XeMH8q
OdMH6HU6d3F15E2eEg221it/TOVTjbHWVr2zv7+fagwgqwqVFQmba4mm78yHVaLd
k0misT6QK6DcjEq0DJVo+6hE20Ulerz2pcc4CInketr2qJy3Et1Pazd17AUunkEk
LxQOc2l1SbSjXz/d3b7b4wZ5SzSgsql2NQTbYyxxoXJOJZrqErU3ientQNASrTmi
ZahEy1CJto9KtF1UosdrHwK5sTT7LFfvKPDiOt0gp7j6RkHlvJVo6bKLcfI6IyMK
lU08dvTp3t7NW4i7wIVEY4w9kHJXw/4YSym7VM5LiZ607b5jgpboom7QkK082W63
lrh2x0UlWobr9lyhEm0HlehwJRpActJuxoL0qt0oeg9XHweV8VaiV2ZPf4uLZZid
KHonVz6JldkpUf1FpLtzIdHgYIyl29XwYIx17pb2CZVxKtFL0/f8iKt/GF3OwfdL
3mSSaNxQuAJ5w8ViE9vioRItYxIlGsecJ7YfCItEJTpsiQbj7GqI74807zd93kuJ
lqa1q547/Q3pC4XDdISZKtCfrmXLlUSDgzGWTqQPx9gdXH3D0OedSrS+WGgmaImu
nD35Pa5A3nCx2EQl+gBIGBczUImWY5Jo7vMKj0p0+BINIDmV++8VpWWLkW4PTp/1
UqI3KsJNUZr1940bF2ZhF6eP/4SrdxjX6e5cSjQYZ3twXKdpjN3G1TcIfdapRNOD
1VepvsSxoynu+H7Jm0wSjZ9BuAJ5w8ViE5XoA1Si7aASbYc0Eq07FspxLdEAqcLS
bg8u2dWQPuedREvT2mF9btbtuS8Ls3+4TnfnWqIB+n35zL2pRJoe1r5DY+xVXH0x
9DmnEr2xOPMM1Zd4TiFzKtFmCtuxEF9uLiCAp1+uUJ5wcdhEJfoAlWg7qETbQSW6
PBINIDlLZ47/lGtrFEkx0Ge8k2hpWjscW9bMGdhcieoS9YHLdHdFSDTAGFucPv5j
rq1R4AGDvGbkwwx9xqlEI32faJmObvvN9ssghUk0fkrjAgJ4K5grlCdcHDZRiT5A
JdoOKtF2UIkul0QD3D8Wpo69yLU3iqu1Kt2V+Djo372SaEwyzZ+U5XCOos5xGzFJ
M1S4THdXlEQDGmN30hj7OdfeKLA0YlQc9O9OJbrdrLeovsS+w2QnXfdex9VRZoKQ
aGyqwgUEID5coTxBm1mBvHLHA1SiD0A/cTEDlWg5KtF2UIkun0SDvkifOvIy1+Yo
Rq0dpn/zSqKlae3wftG4LxQOs91pLUpmLl2muytSogFEmo73Ja7NUVwe8aKedK21
LYnu9aKjJImiXRInMVd0EBINgeECAkW9XJiVwxsye0wq0QeoRNtBJdoOKtHllGiA
7BVpRXq73Z4djof+7pVE0/3xea59X3CV7q5oiQYYYyTSol8FYlqN2kPD8biWaLwk
uXDq7l9wbQyDpSiTti46CInGSTSti8Y6LK6gz/gi0ZvLc1/kyviASrQdVKLtoBJd
XokGkBxqR3R+Ae5J3aF1vfR3byRaOiNcJLg2uZi59EGiQX+MnZTN6sZEra0HBpe9
SLNl2JJoQA7xFaozsU18JyZtSUcQEo3/2Fic+TIXFID8DBfyHZcSDVHm2gEQbK6M
DzTWKo9zMQOVaDkq0XZQiS63RAPkOqa2xCLd3yij231LXJ7+5o1ES9PaFY2LdHe+
SDRobzVE+bRj+g9r3c6JuI+kQmtTopu16sPSmCdtSUcwEg2J4YICIS7pcCnRJhmF
YHFlfAD9wMUM0H9cmSyoRCsmVKLLL9Gg02o8SO2J5RPfryiK3oiy9P+9kGj8Ouv7
LHSMi3R3Pkk0aG/VH0xzfvCwRteU/mYsm8tzn6e/OZXoNOuisWHPJC3pCEaik5Z0
hLYzmkuJNsnh4vQ9P+PK+IBpGUoeWVlUohUTKtGTIdGgVV/fpTbFIh1vxkL/2wuJ
lqa184W80935JtEgzewuqJy975+xGQvF+AT9f6cSDaj971K9ojE1SbPRwUg0MC3p
gAwWkTN6XFxKtGkWH/jab8bUhr3eG7gyWVCJVkyoRE+ORIO0Io0ZVfpv0efzlOg0
ae18Ie90dz5KNEgr0hhjhx6UOM5sS3S7UYukscLH6Bo4EWujg5LoJBmEBA0W9BmX
Eo1Zeq6dGMTClSsSSDIXawxXJisq0YoJlejJkmgg7Zu05CnR0rR2PoFfmbPulmjC
V4kG1KZoZjkttiU6TZYOMCpFX9kISqKBaXby8M1Q6zOUeeBSorvd6BjXToyPDx+m
ByZIIVcmKyrRigmV6MmTaJCHSOcp0Suzp7/Ftek7eaa781miQR4ibVuigXT3wphu
1DpSxHfWJcFJtEk+gc8p2wZxKdH4eQ8vJnBtAR8zdJg22LHdPzEq0YoJlejJlGiw
sTT7LMVgTXLykmikUJNKTtRqzWFM5410fB1s+JKPwPou0bhHS3d6lJKHRCPOpel7
fsS1x4GtwOlaeEeZRTo4iQamlG0ghGUduLhwsYM8JNEkpb7N4CMW00ukUbu5xpXL
ikq0YuLwO6sSzdSRhRAkGvJgU6TzkmhpWruNC3NP29qhMAlcz6lNkdjnle7Od4kG
tkU6D4kGUau5mCbXddlFOkiJ3tnZebNJskCrsf7B4XI+4VqiTcsjwNb6xUe5ckWA
WLgYAc471mZx5bKiEq2YUImeXIkGkBxprEnkIdG4L1LdslnoqHPcZV9uXEgj9/Yl
NgSJBri3rcxNfZNiySzSeUk0kKbZiymzSAcp0aBZq36cC3IQn8XHtUTjy8m1FePL
bDRiMD0g5bn0RCVaMaESPdkSDQ4k5/S3ufjSkIdES9Pa4b0iV7PQMcgzLF1mshNF
7+TqyEIoEg0wxtKkkxtFnhKN+3SalwxBX6S73XeVTaSDlWjMCpjkIMZX+XEt0SBp
GYwPs9GmWWjQbjbaXDkbqEQrJlSiVaIBJOfizMnnuRil2JZo3A8Xp4//hGtrGLqG
Xi6iH1dmp0QvPOaR7i4kiQb4VYGk8/tcjFLylGiQJuVdDCbImvX1D/vQx7YIVqJB
f6AJRBqz1rjIcHUURRESjQ1KuPYGKXLTmqRUfDjXeZ5HlWjFhEq0SnQM7j2V++/9
ARenBNsSLd1l8WA/hfxSyZnAluoS6TpYstd7LVfHuIQm0QBjbGHq6M+5OCXkLdG4
F28szjxDbYmuiYMg3zVdI9/E1esScqI7s/ZR0BINsL2pKfNETPX89NfxWa6OIihC
okHSbDT6soh+guCblnGAvAVfJVoxoRKtEj0IJGfx9LEXuFiTsC3R0rR2VzZXrxfV
h6lmyy2nuwtRogEkb2Hq2FginbdEgywiDddobq5+hK6V/S3zXYJ+3bgw9xQehGdm
Zm7lPiMleIkGEgEDOGl5ZXZIS1ESTQPWuOYYQLpcijTOX9IvCljHx5W1iUq0YkIl
WiV6GFy7SHJe5OI1YVOipWntcN3vRZFzYRnkSm3tYxRL4ljDjLlNmQ1VogHWk9O5
e4mL14QLiQZZRBpgXNary39OD6VvyTNeLMOi+/ilzaXZX2ZA2ayc+5uVlZVXcJ+X
UgqJBtudzoxEpAFeTsPnuXpcgBlVk9jkKdFA8lImHjhc9BHWOEvOG25WXHmbqEQr
JlSiVaI5sJnVwqkjL3Mxj8KmREvT2tUq5z+3X3D/9SdxhFuS20x3F7JEAzwo0X0y
1VburiQaZBXpGCzzwK8Q3Sh6j43Yd3u9t2EZUY2+I9yDZru+0c16vksj0QDSJ1na
EYPZTZcz04gPy0q4WAbJW6LB4f77bPuDQCzxBMfVkQX8FGrKXT1Ini8TDqISrZhQ
iVaJHgUkJ41I25Jo/GIofbmr2+ncxdXhGpL5z1A8ieOteu70N2wJbegSDbY7rVT5
mV1KNLAl0jGYXINUX61VH2lv1d5PsjqFazDGPI5rd3f3dpxX/C0GW95fXqt84vCa
khhHFHXuzdpHaSS6CK5urP4hG/goIGcSUR0EkoG80phR4OrMAk5sY63yOH6e4trm
cCHRGPDSfsKDiS2ZxvnB8XHtcKBdrp48UIlWTOC7TH2mEs3UkYUySDToS45wfNiS
aJ/T2o0CvypSTCLx71kS/zJINGhvNeoUp/Chya1EA3hFc3P1o2mzdhRFFEWv544j
DaWT6BjJkgUOPP3g5Ts8+aRdFwxBxFINyBiWjKSZFY9BGVfCBik2CdYw6BvMYOOB
Q7q8Al8qzMDjfKR9uHHxMDGISaKxJS3OaRFgxp6LV4pKtB1UolWik8BPxxRrYl/a
kGhcW1MsjVj3qe+k6e5sSW1ZJBq0m/WWRFKLkOgYrOOunD2VOdd1niBvddaXCkFp
JRrgppdmBtgE6uEEB3CfHwfIO9aMcceSF2gvrdwOYpLLcR4iYiDdXLx5YpLoIoEE
c/FKUYm2g0q0SrQESbo5GxKNn66prsTzVmRau1FEnVZV/DJkL/vLkGWSaED3x4eT
+q9IiQa+z0rXVhc+nfWlQlBqiQaYbcVyCnwZuQZ8AJJT5IuOALPLPvQRLviQFS7G
vFGJVkyoRKtES2nV13cp5pF9akOiK2dlG75gTalv/QbBcpnurmwSDZIEtWiJjona
7bPLZ+7FxjGia6crbLxUCEov0TGYccXsZpbZUdtAbiCvuKBwMbsGa8Ixs8zF6gLM
xOfxEqMUlWjFhEq0SnQarhrSuWWVaKy/Fs/kFpzWbhStxkaPYkwcdzZm0sso0YDi
fYLiZvvQF4mOidrN1er56a9RbKJraN7YeKkQTIxEx0DSIEu2lnmMA9a4Fj3zbAJr
sl3KNOQ5j5c606ISrZhQiVaJTsuovs0q0dK0do3q8ieLTms3CkxsuUp3V1aJBqOy
nfgm0TFYL31pdemJopZ5YCIVm7xcv37dyhKniZPoGMz+QhbpIvcpF0KNdcf9F/Ic
r3nOAkQfa5u548kKZkjQ93gZk2u7CFSiFRMq0SrR43Dp4vxfU/w39W8WiQ4xrd0o
SPL/jOJMHHtZ092VWaLhMlxqOV8lOgYuhLXda+en/3E49jzAi4TtRu0hW/IcM7ES
PQwuTMjIgVnRrEs+UL6fxYKkDDdeX5ZrjAsGO/JpY215lhlqCDn6BHLuY59A6HG+
fCPrLD3Kc/UC7vMKD37F4vqQI6TvPK593DEMkzZbkRRk+uHaGyav9vOmLzlLs8/S
NfCXopBFonE95vpnGB9+3UtCeiwgixDiuwuR5uodJOQxRvfXrwyOMd8lehDEj1zr
WAJlS6oxUbdxYe7pdrP+PrrGvCOvvpCOraLAhA4beN4MfrkxYw35A5DsWJBjsBlI
/NlQv4RpiPsmTucXA0nGUpVf/q2x/sG4X7h6FEVRJgFIAmb8cY0E2JGN+5yijAtk
jqTxqXiM9bqdu0KR6GHwfYnFtO8Z9fVdOAUm8vDLVXyM+OUAL87GzrHdbs+izP7+
fpDHnRfsHxVFURRFURRFGcUjt/w/a9cyx591OVIAAAAASUVORK5CYII=</fo:instream-foreign-object>
                                                </fo:block>
                                             </fo:table-cell>
                                             <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="46.65pt" number-columns-spanned="1">
                                                <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="12.0pt"/>
                                             </fo:table-cell>
                                          </fo:table-row>
                                       </xsl:for-each>
                                    </fo:table-body>
                                 </fo:table>
                              </fo:block>
                              <fo:block/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="42.25pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:tab-stops="center:234.0pt:space right:468.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="11.0pt" height="12.716001pt"/>
            </fo:static-content>
            <fo:static-content flow-name="region-footer">
               <fo:block padding-bottom="0.0pt" padding-top="0.0pt">
                  <fo:table start-indent="-62.1pt" style-id="ts17" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 3" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="120.6pt"/>
                     <fo:table-column column-width="120.6pt"/>
                     <fo:table-column column-width="120.6pt"/>
                     <fo:table-column column-width="120.6pt"/>
                     <fo:table-column column-width="116.1pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="5">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                 <fo:inline font-size="11.0pt" white-space-collapse="false" height="11.0pt" font-family="Calibri" font-weight="bold" color="#1f497d">This is a computer generated document and does not require signature</fo:inline>
                                 <fo:inline height="10.0pt" white-space-collapse="false" font-size="10.0pt" color="#1f497d" font-family="Calibri">.</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="5">
                              <fo:block height="11.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="5">
                              <fo:block height="11.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="7.2pt" number-columns-spanned="1">
                              <fo:block-container writing-mode="rl-tb">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline height="6.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="6.0pt">PO Box 35356</fo:inline>
                                 </fo:block>
                              </fo:block-container>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="6.0pt" font-family="Calibri" white-space-collapse="false" font-size="6.0pt">T.+971 4 405 0000</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="1">
                              <fo:block-container writing-mode="rl-tb">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline xml:space="preserve" height="8.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="8.0pt">هاتف: ٠٠٠٠ ٤٠٥ ٤ ٩٧١</fo:inline>
                                 </fo:block>
                              </fo:block-container>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="1">
                              <fo:block-container writing-mode="rl-tb">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline xml:space="preserve" height="8.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="8.0pt">ص.ب. ٣٥٣٥٦، دبي</fo:inline>
                                 </fo:block>
                              </fo:block-container>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:basic-link external-destination="http://www.gulffinance.com/">
                                    <fo:inline height="6.0pt" font-family="Calibri" white-space-collapse="false" font-size="6.0pt" color="#0000ff" text-decoration="underline">www.gulffinance.com</fo:inline>
                                 </fo:basic-link>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="7.2pt" number-columns-spanned="1">
                              <fo:block-container writing-mode="rl-tb">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline height="6.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="6.0pt">United Arab Emirates</fo:inline>
                                 </fo:block>
                              </fo:block-container>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="6.0pt" font-family="Calibri" white-space-collapse="false" font-size="6.0pt">F.+971 4 3307144</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="1">
                              <fo:block-container writing-mode="rl-tb">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline xml:space="preserve" height="8.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="8.0pt">فاكس: ٧١٤٤ ٣٣٠ ٤ ٩٧١</fo:inline>
                                 </fo:block>
                              </fo:block-container>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="1">
                              <fo:block-container writing-mode="rl-tb">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline xml:space="preserve" height="8.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="8.0pt">الامارات العربية المتحدة</fo:inline>
                                 </fo:block>
                              </fo:block-container>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="6.0pt" font-family="Calibri" white-space-collapse="false" font-size="6.0pt">info@gulf-finance.com</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="5">
                              <fo:block-container writing-mode="rl-tb">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline xml:space="preserve" height="6.5pt" font-family="Times New Roman" white-space-collapse="false" font-size="6.5pt">رأس المال المصدر و المدفوع ١٤٠ مليون درهم.</fo:inline>
                                    <fo:inline xml:space="preserve" height="6.5pt" font-family="Calibri" white-space-collapse="false" font-size="6.5pt"> </fo:inline>
                                    <fo:inline xml:space="preserve" height="6.5pt" font-family="Times New Roman" white-space-collapse="false" font-size="6.5pt">شركة الخليج للتمويل (ش.م.خ) شركة تمويل مرخصة و تعمل تحت مظلة المصرف المركزي لدولة الامارات العربية المتحدة.</fo:inline>
                                    <fo:inline xml:space="preserve" height="6.5pt" font-family="Calibri" white-space-collapse="false" font-size="6.5pt">   </fo:inline>
                                    <fo:inline xml:space="preserve" height="6.5pt" font-family="Times New Roman" white-space-collapse="false" font-size="6.5pt">المكتب الرئيسي ص.ب. ٣٥٣٥٦ دبي. ا.ع.م. رقم التسجيل</fo:inline>
                                    <fo:inline xml:space="preserve" height="6.5pt" font-family="Calibri" white-space-collapse="false" font-size="6.5pt"> </fo:inline>
                                    <fo:inline xml:space="preserve" height="6.5pt" font-family="Times New Roman" white-space-collapse="false" font-size="6.5pt">التجاري ٥١٥٢٠</fo:inline>
                                 </fo:block>
                              </fo:block-container>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="5">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="5.5pt" font-family="Calibri" white-space-collapse="false" font-size="5.5pt">Nominated and Paid-Up Share Capital AED 140 Million. Gulf Finance Corporation PJSC is a finance company licensed and regulated by the UAE Central Bank, Head Office:  PO Box 35356 Dubai, UAE Commercial Registration # 51520</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="5">
                              <fo:block-container writing-mode="rl-tb">
                                 <fo:block xdofo:tab-stops="center:234.0pt:space right:468.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                    <fo:inline xml:space="preserve" height="9.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="9.0pt">الخليج للتمويل (فرع) مسجل و مرخص لدى المنطقة الحرة كشركة قانونية في</fo:inline>
                                 </fo:block>
                              </fo:block-container>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="7.2pt" number-columns-spanned="5">
                              <fo:block xdofo:tab-stops="center:234.0pt:space right:468.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="9.0pt" font-family="Calibri" white-space-collapse="false" font-size="9.0pt">Gulf Finance Corporation PJSC - DMCC branch is registered and Licensed as a FREEZONE Company under the rules and regulations of the DMCCA</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:tab-stops="center:234.0pt:space right:468.0pt:space" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="11.0pt" height="12.716001pt"/>
            </fo:static-content>
            <fo:flow flow-name="region-body">
               <fo:block padding-bottom="0.0pt" padding-top="0.0pt">
                  <fo:table start-indent="0.0pt" style-id="ts17" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 5" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="99.9pt"/>
                     <fo:table-column column-width="139.5pt"/>
                     <fo:table-column column-width="63.0pt"/>
                     <fo:table-column column-width="49.5pt"/>
                     <fo:table-column column-width="99.0pt"/>
                     <fo:table-column column-width="27.9pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="13.9pt" number-columns-spanned="2">
                              <fo:block xdofo:xliff-note="BILL_TO_CUSTOMER_NAME" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">
                                    <xsl:value-of select=".//BILL_TO_CUSTOMER_NAME" xdofo:field-name="BILL_TO_CUSTOMER_NAME"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="13.9pt" number-columns-spanned="4">
                              <fo:block xdofo:xliff-note="TRX_DATE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Invoice Date       : <xsl:value-of select=".//TRX_DATE" xdofo:field-name="TRX_DATE"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="13.85pt" number-columns-spanned="2">
                              <fo:block xdofo:xliff-note="BILL_TO_ADDRESS1" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">
                                    <xsl:value-of select=".//BILL_TO_ADDRESS1" xdofo:field-name="BILL_TO_ADDRESS1"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="13.85pt" number-columns-spanned="4">
                              <fo:block xdofo:xliff-note="TRX_NUMBER" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Invoice Number : <xsl:value-of select=".//TRX_NUMBER" xdofo:field-name="TRX_NUMBER"/> </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="6">
                              <fo:block xdofo:xliff-note="BILL_TO_ADDR5" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">
                                    <xsl:value-of select=".//BILL_TO_ADDR5" xdofo:field-name="BILL_TO_ADDR5"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="6">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="6">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="6">
                              <fo:block xdofo:xliff-note="TITLE, FIRST_NAME, LAST_NAME, MIDDLE_NAME" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">For the Attention of : <xsl:value-of select=".//TITLE" xdofo:field-name="TITLE"/> <xsl:value-of select=".//FIRST_NAME" xdofo:field-name="FIRST_NAME"/> <xsl:value-of select=".//LAST_NAME" xdofo:field-name="LAST_NAME"/> <xsl:value-of select=".//MIDDLE_NAME" xdofo:field-name="MIDDLE_NAME"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="6">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="27.85pt" number-columns-spanned="5" border-bottom="0.5pt solid #000000">
                              <fo:block xdofo:xliff-note="TITLE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Dear <xsl:value-of select=".//TITLE" xdofo:field-name="TITLE"/></fo:inline>
                              </fo:block>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="12.0pt" height="12.0pt"/>
                              <fo:block xdofo:xliff-note="if, CLASS, TRX" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Please find below our <xsl:call-template name="sql_af4b7ca9_0"/><xsl:value-of select="xdoxslt:get_variable($_XDOCTX, '_FXRSLT')"/></fo:inline>
                                 <fo:inline xml:space="preserve" font-size="11.0pt" white-space-collapse="false" height="11.0pt" font-family="Calibri"> </fo:inline>
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt"><xsl:call-template name="sql_42e9a1d_1"/><xsl:value-of select="xdoxslt:get_variable($_XDOCTX, '_FXRSLT')"/> for <xsl:value-of select=".//TRX_MONTH" xdofo:field-name="TRX_MONTH"/>.</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.15pt" padding-bottom="0.0pt" padding-start="5.15pt" padding-top="0.0pt" vertical-align="top" height="19.7pt" number-columns-spanned="5" border-top="0.5pt solid #000000" border-bottom="0.5pt solid #000000" border-start-style="solid" border-start-width="0.5pt" border-start-color="#000000" border-end-color="#000000" border-end-style="solid" border-end-width="0.5pt">
                              <fo:block xdofo:xliff-note="ICC" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt" font-weight="bold">                                                                                                             Amount in <xsl:value-of select=".//INVOICE_CURRENCY_CODE" xdofo:field-name="INVOICE_CURRENCY_CODE"/></fo:inline>
                              </fo:block>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:table start-indent="0.0pt" style-id="ts17" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 4" xdofo:row-header-count="0">
                                    <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                                    <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                                    <fo:table-column column-width="223.25pt"/>
                                    <fo:table-column column-width="223.3pt"/>
                                    <fo:table-body>
                                       <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                                       <xsl:variable name="_XDOFOTOTAL" select="count(.//G_AR_DTL_GROUP)"/>
                                       <xsl:for-each select=".//G_AR_DTL_GROUP" xdofo:ctx="3">
                                          <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                                          <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                                          <fo:table-row xdofo:repeat="R">
                                             <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="19.6pt" number-columns-spanned="1">
                                                <fo:block xdofo:xliff-note="F , LINE_DESCRIPTION" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                                   <fo:inline height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">
                                                      <xsl:value-of select=".//LINE_DESCRIPTION" xdofo:field-name="LINE_DESCRIPTION"/>
                                                   </fo:inline>
                                                </fo:block>
                                             </fo:table-cell>
                                             <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="19.6pt" number-columns-spanned="1">
                                                <fo:block xdofo:xliff-note="     ,  E" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                                   <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt" font-weight="bold">                                                 </fo:inline>
                                                   <fo:inline height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">
                                                      <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv1">
                                                         <xsl:value-of select=".//LINE_AMOUNT" xdofo:field-name="LINE_AMOUNT"/>
                                                      </xsl:variable>
                                                      <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv1, '#,##0')"/>
                                                   </fo:inline>
                                                   <fo:inline height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt" font-weight="bold">/-</fo:inline>
                                                </fo:block>
                                             </fo:table-cell>
                                          </fo:table-row>
                                       </xsl:for-each>
                                    </fo:table-body>
                                 </fo:table>
                              </fo:block>
                              <fo:block/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.15pt" padding-top="0.0pt" vertical-align="top" height="19.7pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-bottom="0.5pt solid #000000" border-start-style="solid" border-start-width="0.5pt" border-start-color="#000000">
                              <fo:block xdofo:xliff-note="ICC, TOTAMT" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt" font-weight="bold">   (<xsl:value-of select=".//INVOICE_CURRENCY_CODE" xdofo:field-name="INVOICE_CURRENCY_CODE"/> <xsl:value-of select=".//TOTAMT_TEXT" xdofo:field-name="TOTAMT_TEXT"/> Only)</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="19.7pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-bottom="0.5pt solid #000000">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt" font-weight="bold">Total:</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.15pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="19.7pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-bottom="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid">
                              <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt" font-weight="bold"> <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv2"><xsl:value-of select=".//TOTAMT" xdofo:field-name="TOTAMT"/></xsl:variable><xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv2, '#,##0')"/>/-                                                                     </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.6pt" number-columns-spanned="1" border-top="0.5pt solid #000000">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Payment Terms </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.6pt" number-columns-spanned="4" border-top="0.5pt solid #000000">
                              <fo:block xdofo:xliff-note="PAYMENT_TERM" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">: <xsl:value-of select=".//PAYMENT_TERM" xdofo:field-name="PAYMENT_TERM"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.85pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.85pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt" font-weight="bold" text-decoration="underline">Bank Details  :</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Bank Name      </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block xdofo:xliff-note="BANK_NAME" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">: <xsl:value-of select=".//BANK_NAME" xdofo:field-name="BANK_NAME"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Account Name </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">: Gulf Finance Corporation PJSC.</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Bank Address  </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block xdofo:xliff-note="BANK_BRANCH_NAME" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">: <xsl:value-of select=".//BANK_BRANCH_NAME" xdofo:field-name="BANK_BRANCH_NAME"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">Account No     </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block xdofo:xliff-note="BANK_ACCOUNT_NUM" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">: <xsl:value-of select=".//BANK_ACCOUNT_NUM" xdofo:field-name="BANK_ACCOUNT_NUM"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">IBAN               </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block xdofo:xliff-note="IBAN_NUMBER" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline xml:space="preserve" height="12.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="12.0pt">: <xsl:value-of select=".//IBAN_NUMBER" xdofo:field-name="IBAN_NUMBER"/></fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="4">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.05pt" number-columns-spanned="5">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" font-family="Times New Roman" font-size="11.0pt" height="11.0pt"/>
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Times New Roman" white-space-collapse="false" font-size="10.0pt" font-weight="bold">NOTE: To ensure prompt allocation of payment always quote the invoice number with your payment</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="center" padding-bottom="10.0pt" end-indent="5.4pt" padding-top="0.0pt" font-family="Calibri" font-size="11.0pt" height="0.0pt">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
   <xsl:template name="sql_af4b7ca9_0">
      <!--Expression: if COMPLETE_FLAG='N'  then  'draft' end if-->
      <xsl:variable name="v1" select="xdoxslt:normalize_string($_XDOCTX, .//COMPLETE_FLAG)='N'"/>
      <xsl:value-of select="xdoxslt:set_variable($_XDOCTX, 'v2t', string(''))"/>
      <xsl:choose>
         <xsl:when test="$v1">
            <xsl:value-of select="xdoxslt:set_variable($_XDOCTX, 'v2t','draft')"/>
         </xsl:when>
      </xsl:choose>
      <xsl:variable name="v2" select="xdoxslt:get_variable($_XDOCTX, 'v2t')"/>
      <xsl:value-of select="xdoxslt:set_variable($_XDOCTX, '_FXRSLT', $v2)"/>
   </xsl:template>
   <xsl:template name="sql_42e9a1d_1">
      <!--Expression: lower(CLASS)-->
      <xsl:variable name="v3" select="translate(string(xdoxslt:normalize_string($_XDOCTX, .//CLASS)), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')"/>
      <xsl:value-of select="xdoxslt:set_variable($_XDOCTX, '_FXRSLT', $v3)"/>
   </xsl:template>
</xsl:stylesheet>
