<?xml version = '1.0' encoding = 'utf-8'?>
<!-- $Header: TEMPLATE_XXSC_XXSCFINPRN_INVU_en.xsl 115.0 2016/05/23 09:25:38 xdouser noship $ -->
<!-- dbdrv: none -->

<!--Generated by Oracle BI Publisher 10.1.3.4.2-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0-fp" margin-left="37.15pt" margin-right="37.15pt" page-height="595.35pt" page-width="842.0pt" margin-top="36.0pt" margin-bottom="36.0pt">
               <fo:region-before region-name="region-header-fp" extent="36.0pt"/>
               <fo:region-body region-name="region-body" margin-top="36.0pt" margin-bottom="36.0pt"/>
               <fo:region-after region-name="region-footer-fp" extent="36.0pt" display-align="after"/>
            </fo:simple-page-master>
            <fo:simple-page-master master-name="master0" margin-left="37.15pt" margin-right="37.15pt" page-height="595.35pt" page-width="842.0pt" margin-top="36.0pt" margin-bottom="36.0pt">
               <fo:region-before region-name="region-header" extent="36.0pt"/>
               <fo:region-body region-name="region-body" margin-top="36.0pt" margin-bottom="36.0pt"/>
               <fo:region-after region-name="region-footer" extent="36.0pt" display-align="after"/>
            </fo:simple-page-master>
            <fo:page-sequence-master master-name="master0-fplr">
               <fo:repeatable-page-master-alternatives>
                  <fo:conditional-page-master-reference master-reference="master0-fp" page-position="first"/>
                  <fo:conditional-page-master-reference master-reference="master0" page-position="rest"/>
               </fo:repeatable-page-master-alternatives>
            </fo:page-sequence-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0-fplr">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(842.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(595.35)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(42.550003)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(42.550003)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header-fp">
               <fo:block xdofo:line-spacing="multiple:13.8pt" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="10.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt" height="0.0pt">
                  <xsl:call-template name="header">
                     <xsl:with-param name="_XDOFOPOS" select="$_XDOFOPOS"/>
                     <xsl:with-param name="_XDOFOPOS2" select="$_XDOFOPOS2"/>
                     <xsl:with-param name="_XDOFOOSTOTAL" select="$_XDOFOOSTOTAL"/>
                     <xsl:with-param name="_XDOFOTOTAL" select="$_XDOFOTOTAL"/>
                     <xsl:with-param name="_SECTION_NAME" select="$_SECTION_NAME"/>
                  </xsl:call-template>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt">
                  <fo:table start-indent="-22.95pt" style-id="ts15" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="815.1pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="11.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="10.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt" height="0.0pt" font-size="11.0pt" font-family="Calibri"/>
            </fo:static-content>
            <fo:static-content flow-name="region-footer-fp"/>
            <fo:static-content flow-name="region-header"/>
            <fo:static-content flow-name="region-footer"/>
            <fo:flow flow-name="region-body">
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt" height="4.624pt" font-size="4.0pt" font-family="Calibri"/>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.25pt" end-indent="5.4pt" padding-top="0.25pt">
                  <fo:table start-indent="-22.95pt" style-id="ts15" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 2" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="51.45pt"/>
                     <fo:table-column column-width="22.6pt"/>
                     <fo:table-column column-width="3.25pt"/>
                     <fo:table-column column-width="12.5pt"/>
                     <fo:table-column column-width="3.7pt"/>
                     <fo:table-column column-width="59.65pt"/>
                     <fo:table-column column-width="30.1pt"/>
                     <fo:table-column column-width="33.3pt"/>
                     <fo:table-column column-width="22.2pt"/>
                     <fo:table-column column-width="16.0pt"/>
                     <fo:table-column column-width="8.15pt"/>
                     <fo:table-column column-width="28.8pt"/>
                     <fo:table-column column-width="19.5pt"/>
                     <fo:table-column column-width="6.7pt"/>
                     <fo:table-column column-width="29.9pt"/>
                     <fo:table-column column-width="6.8pt"/>
                     <fo:table-column column-width="5.9pt"/>
                     <fo:table-column column-width="64.3pt"/>
                     <fo:table-column column-width="2.9pt"/>
                     <fo:table-column column-width="33.5pt"/>
                     <fo:table-column column-width="17.95pt"/>
                     <fo:table-column column-width="40.2pt"/>
                     <fo:table-column column-width="16.65pt"/>
                     <fo:table-column column-width="6.65pt"/>
                     <fo:table-column column-width="35.85pt"/>
                     <fo:table-column column-width="17.9pt"/>
                     <fo:table-column column-width="30.85pt"/>
                     <fo:table-column column-width="187.85pt"/>
                     <fo:table-body>
                        <fo:table-row keep-together="always">
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="28">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                 <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="14.0pt" font-size="14.0pt" font-weight="bold">
                                    <xsl:value-of select="//OU_NAME" xdofo:field-name="//OU_NAME"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row keep-together="always">
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="28">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                 <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="14.0pt" font-size="14.0pt" font-weight="bold">Invoice Voucher</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                        <xsl:variable name="_XDOFOTOTAL" select="count(.//G_INVOICE)"/>
                        <xsl:for-each select=".//G_INVOICE" xdofo:ctx="22">
                           <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                           <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                           <fo:table-row keep-together="always" xdofo:repeat="R">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="1.4pt" vertical-align="top" height="14.2pt" number-columns-spanned="3"/>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="1.4pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="1.4pt" padding-top="1.4pt" vertical-align="top" height="14.2pt" number-columns-spanned="16">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="1.4pt" vertical-align="top" height="14.2pt" number-columns-spanned="3">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Invoice Type</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="1.4pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">: <xsl:value-of select=".//INVOICE_TYPE_LOOKUP_CODE" xdofo:field-name="INVOICE_TYPE_LOOKUP_CODE"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="1.4pt" padding-top="1.4pt" vertical-align="top" height="14.2pt" number-columns-spanned="16">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Narration:</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="3">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Invoice Number</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">: <xsl:value-of select=".//INVOICE_NUM" xdofo:field-name="INVOICE_NUM"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="1.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="14" number-rows-spanned="5" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                       <xsl:value-of select=".//NARRATION" xdofo:field-name="NARRATION"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="0.0pt" overflow="hidden" number-rows-spanned="5" wrap-option="no-wrap" padding-top="0.0pt" padding-start="0.0pt" number-columns-spanned="2" padding-bottom="0.0pt" vertical-align="top" height="14.2pt">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="3">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Invoice Date</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">: <xsl:value-of select=".//INVOICE_DATE" xdofo:field-name="INVOICE_DATE"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="3">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Invoice Status</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">: <xsl:value-of select=".//CF_INVOICE_STATUS" xdofo:field-name="CF_INVOICE_STATUS"/> And <xsl:value-of select=".//CF_ASTATUS" xdofo:field-name="CF_ASTATUS"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="3">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Approval Status</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">: <xsl:value-of select=".//APPROVAL" xdofo:field-name="APPROVAL"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="3">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">GL Date</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">: <xsl:value-of select=".//GL_DATE" xdofo:field-name="GL_DATE"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="3">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Voucher Number</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">: <xsl:value-of select=".//DOC_SEQ" xdofo:field-name="DOC_SEQ"/></fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="4">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Supplier :</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="10">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                       <xsl:value-of select=".//SUP_NAME" xdofo:field-name="SUP_NAME"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="2">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always">
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="3">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="9">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="4">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="10">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="14.2pt" number-columns-spanned="2">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row keep-together="always" keep-with-next="always">
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">A/C No.</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Sub A/C No.</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">A/C Description</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Sub-A/C Description</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Dept No.</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="4" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Dept Description</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Region</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Region Description</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Product/</fo:inline>
                                 </fo:block>
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Project</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Product/</fo:inline>
                                 </fo:block>
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Project Description</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">CCY</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">EC Amount</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt" background-color="#a6a6a6">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">FC Amount</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                           <xsl:variable name="_XDOFOTOTAL" select="count(.//G_ACCT_DISTRIBUTIONS)"/>
                           <xsl:for-each select=".//G_ACCT_DISTRIBUTIONS" xdofo:ctx="3">
                              <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                              <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                              <fo:table-row keep-together="always" xdofo:repeat="R">
                                 <fo:table-cell vertical-align="middle" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="fe,      " orphans="2" widows="2" linefeed-treatment="preserve" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select=".//SEGMENT4" xdofo:field-name="SEGMENT4"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//SEGMENT5,'  ')" xdofo:field-name="concat(SEGMENT5,'  ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//CF_ACT_DESC,'  ')" xdofo:field-name="concat(CF_ACT_DESC,'  ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//CP_SUBAC_DESC,'  ')" xdofo:field-name="concat(CP_SUBAC_DESC,'  ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//SEGMENT3,'  ')" xdofo:field-name="concat(SEGMENT3,'  ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="4" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//CP_DEPT_DESC,' ')" xdofo:field-name="concat(CP_DEPT_DESC,' ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//REGION,'  ')" xdofo:field-name="concat(REGION,'  ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//CP_REGIONDESC,' ')" xdofo:field-name="concat(CP_REGIONDESC,' ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//SEGMENT6,'  ')" xdofo:field-name="concat(SEGMENT6,'  ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="0.0pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select="concat(.//CP_PRODUCTDESC,' ')" xdofo:field-name="concat(CP_PRODUCTDESC,' ')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="CC" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:value-of select=".//CP_INV_CUR_CODE" xdofo:field-name="CP_INV_CUR_CODE"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="0.00" orphans="2" widows="2" linefeed-treatment="preserve" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0pt">
                                       <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                          <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv1">
                                             <xsl:value-of select=".//CF_ENTERED_AMT" xdofo:field-name="CF_ENTERED_AMT"/>
                                          </xsl:variable>
                                          <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv1, '#,##0.00')"/>
                                       </fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                    <fo:block xdofo:xliff-note="0.00, c, e" orphans="2" widows="2" linefeed-treatment="preserve" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0pt">
                                       <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt"> <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv2"><xsl:value-of select=".//CF_FUNCTIONAL_AMT" xdofo:field-name="CF_FUNCTIONAL_AMT"/></xsl:variable><xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv2, '#,##0.00')"/>  <xsl:value-of select=".//CP_ATYPE" xdofo:field-name="CP_ATYPE"/></fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                              </fo:table-row>
                           </xsl:for-each>
                           <fo:table-row>
                              <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="1.15pt" padding-end="5.4pt" number-columns-spanned="5" border-top="0.5pt solid #000000" border-start-style="solid" border-start-width="0.5pt" border-start-color="#000000">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                    <xdofo:tab font-size="11.0pt" font-family="Calibri" color="#000000"/>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.4pt" padding-bottom="1.15pt" padding-end="5.4pt" number-columns-spanned="2" border-top="0.5pt solid #000000">
                                 <fo:block height="12.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.4pt" padding-bottom="1.15pt" padding-end="5.4pt" number-columns-spanned="4" border-top="0.5pt solid #000000">
                                 <fo:block height="12.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.4pt" padding-bottom="1.15pt" padding-end="5.4pt" number-columns-spanned="4" border-top="0.5pt solid #000000">
                                 <fo:block height="12.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.4pt" padding-bottom="1.15pt" padding-end="5.4pt" number-columns-spanned="3" border-top="0.5pt solid #000000">
                                 <fo:block height="12.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.4pt" padding-bottom="1.15pt" padding-end="5.15pt" number-columns-spanned="4" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid">
                                 <fo:block height="12.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="1.15pt" padding-end="5.15pt" number-columns-spanned="5" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="12.0pt" font-size="12.0pt" font-weight="bold">TOTAL:</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="0.0pt" border-bottom="0.5pt solid #000000" padding-top="1.15pt" padding-start="5.15pt" padding-bottom="1.15pt" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="0.00" orphans="2" widows="2" linefeed-treatment="preserve" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="12.0pt" font-size="12.0pt">
                                       <xsl:variable xdofo:ctx="17" xdofo:ctx2="wrapper" name="fv3">
                                          <xsl:value-of select=".//INV_AMT" xdofo:field-name="INV_AMT"/>
                                       </xsl:variable>
                                       <xsl:value-of select="xdoxslt:ms_format_number($_XDOXSLTCTX, $fv3, '#,##0.00')"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Entered by:</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="1.15pt" padding-bottom="0.0pt" padding-end="1.15pt" number-columns-spanned="7" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                       <xsl:value-of select=".//USER_NAME" xdofo:field-name="USER_NAME"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="4" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Checked by:</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="7" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Approved by:</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="5" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                       <xsl:value-of select=".//CF_APPROVER" xdofo:field-name="CF_APPROVER"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                           <fo:table-row>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="2" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Date:</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="1.15pt" padding-bottom="0.0pt" padding-end="1.15pt" number-columns-spanned="7" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                       <xsl:value-of select=".//CREATION_DATE" xdofo:field-name="CREATION_DATE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="4" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Date:</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="7" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block height="11.0pt"/>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="3" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt" font-weight="bold">Date:</fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell vertical-align="top" height="10.85pt" border-bottom="0.5pt solid #000000" padding-top="5.4pt" padding-start="5.15pt" padding-bottom="0.0pt" padding-end="5.15pt" number-columns-spanned="5" border-top="0.5pt solid #000000" border-end-width="0.5pt" border-end-color="#000000" border-end-style="solid" border-start-color="#000000" border-start-style="solid" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="     ,      " orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" start-indent="0.0pt" height="0pt">
                                    <fo:inline white-space-collapse="false" font-family="Calibri" color="#000000" height="11.0pt" font-size="11.0pt">
                                       <xsl:value-of select=".//CP_APPROVAL_DATE" xdofo:field-name="CP_APPROVAL_DATE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                        </xsl:for-each>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
   <xsl:template name="header">
      <xsl:param name="_XDOFOPOS"/>
      <xsl:param name="_XDOFOPOS2"/>
      <xsl:param name="_XDOFOOSTOTAL"/>
      <xsl:param name="_XDOFOTOTAL"/>
      <xsl:param name="_SECTION_NAME"/>
      <xsl:if test="//CF_OPNAME=0">
         <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt" height="0.0pt">
            <fo:external-graphic src="url('{'${OA_MEDIA}/SHUAA.gif'}')" xdofo:alt="An Image" width="171.0pt" height="37.3275pt" xdofo:image-uid="ba60b2ce103fb8c10fc759d981e5c4b2"/>
         </fo:block>
      </xsl:if>
      <xsl:if test="//CF_OPNAME=1">
         <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt" height="0.0pt">
            <fo:external-graphic src="url('{'${OA_MEDIA}/GULF.png'}')" xdofo:alt="An Image" width="170.8875pt" height="37.260002pt" xdofo:image-uid="67e620b7cfa3c2907f6ac3d8fbe04d73"/>
         </fo:block>
         <fo:block orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt">
            <fo:inline xml:space="preserve" white-space-collapse="false" font-family="Calibri" color="#000000" height="12.716001pt" font-size="11.0pt"> </fo:inline>
         </fo:block>
      </xsl:if>
   </xsl:template>
</xsl:stylesheet>
