<?xml version = '1.0' encoding = 'utf-8'?>
<!-- $Header: TEMPLATE_XXSC_XXSC_PROBATION_END_LETTER_en.xsl 115.0 2016/05/23 09:25:40 xdouser noship $ -->
<!-- dbdrv: none -->

<!--Generated by Oracle BI Publisher 10.1.3.4.2-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <xdofo:list-styles>
            <xdofo:list-template template-id="1544826743">
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 ." first-line-indent="-36.0pt" left-indent="54.0pt" before-indent="54.0pt" list-tab="54.0pt"/>
               <xdofo:list-level format-code="255" header-align="before" char-follow="tab" start-at="0" header-text="" first-line-indent="0.0pt" left-indent="0.0pt" before-indent="0.0pt" list-tab="18.0pt"/>
               <xdofo:list-level format-code="255" header-align="before" char-follow="tab" start-at="0" header-text="" first-line-indent="0.0pt" left-indent="0.0pt" before-indent="0.0pt" list-tab="18.0pt"/>
               <xdofo:list-level format-code="255" header-align="before" char-follow="tab" start-at="0" header-text="" first-line-indent="0.0pt" left-indent="0.0pt" before-indent="0.0pt" list-tab="18.0pt"/>
               <xdofo:list-level format-code="255" header-align="before" char-follow="tab" start-at="0" header-text="" first-line-indent="0.0pt" left-indent="0.0pt" before-indent="0.0pt" list-tab="18.0pt"/>
               <xdofo:list-level format-code="255" header-align="before" char-follow="tab" start-at="0" header-text="" first-line-indent="0.0pt" left-indent="0.0pt" before-indent="0.0pt" list-tab="18.0pt"/>
               <xdofo:list-level format-code="255" header-align="before" char-follow="tab" start-at="0" header-text="" first-line-indent="0.0pt" left-indent="0.0pt" before-indent="0.0pt" list-tab="18.0pt"/>
               <xdofo:list-level format-code="255" header-align="before" char-follow="tab" start-at="0" header-text="" first-line-indent="0.0pt" left-indent="0.0pt" before-indent="0.0pt" list-tab="18.0pt"/>
               <xdofo:list-level format-code="255" header-align="before" char-follow="tab" start-at="0" header-text="" first-line-indent="0.0pt" left-indent="0.0pt" before-indent="0.0pt" list-tab="18.0pt"/>
            </xdofo:list-template>
            <xdofo:list-template template-id="1500996035">
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 ." first-line-indent="-18.0pt" left-indent="54.0pt" before-indent="54.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#1 ." first-line-indent="-18.0pt" left-indent="90.0pt" before-indent="90.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#2 ." first-line-indent="-9.0pt" left-indent="126.0pt" before-indent="126.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#3 ." first-line-indent="-18.0pt" left-indent="162.0pt" before-indent="162.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#4 ." first-line-indent="-18.0pt" left-indent="198.0pt" before-indent="198.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#5 ." first-line-indent="-9.0pt" left-indent="234.0pt" before-indent="234.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#6 ." first-line-indent="-18.0pt" left-indent="270.0pt" before-indent="270.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#7 ." first-line-indent="-18.0pt" left-indent="306.0pt" before-indent="306.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#8 ." first-line-indent="-9.0pt" left-indent="342.0pt" before-indent="342.0pt" list-tab="0.0pt"/>
            </xdofo:list-template>
            <xdofo:list-template template-id="1358501645">
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="( #0 )" first-line-indent="-18.0pt" left-indent="54.0pt" before-indent="54.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#1 ." first-line-indent="-18.0pt" left-indent="90.0pt" before-indent="90.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#2 ." first-line-indent="-9.0pt" left-indent="126.0pt" before-indent="126.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#3 ." first-line-indent="-18.0pt" left-indent="162.0pt" before-indent="162.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#4 ." first-line-indent="-18.0pt" left-indent="198.0pt" before-indent="198.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#5 ." first-line-indent="-9.0pt" left-indent="234.0pt" before-indent="234.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#6 ." first-line-indent="-18.0pt" left-indent="270.0pt" before-indent="270.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#7 ." first-line-indent="-18.0pt" left-indent="306.0pt" before-indent="306.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#8 ." first-line-indent="-9.0pt" left-indent="342.0pt" before-indent="342.0pt" list-tab="0.0pt"/>
            </xdofo:list-template>
            <xdofo:list-template template-id="376322420">
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="54.0pt" before-indent="54.0pt" list-tab="0.0pt" font-family="Symbol"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="o" first-line-indent="-18.0pt" left-indent="90.0pt" before-indent="90.0pt" list-tab="0.0pt" font-family="Courier New"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="126.0pt" before-indent="126.0pt" list-tab="0.0pt" font-family="Wingdings"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="162.0pt" before-indent="162.0pt" list-tab="0.0pt" font-family="Symbol"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="o" first-line-indent="-18.0pt" left-indent="198.0pt" before-indent="198.0pt" list-tab="0.0pt" font-family="Courier New"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="234.0pt" before-indent="234.0pt" list-tab="0.0pt" font-family="Wingdings"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="270.0pt" before-indent="270.0pt" list-tab="0.0pt" font-family="Symbol"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="o" first-line-indent="-18.0pt" left-indent="306.0pt" before-indent="306.0pt" list-tab="0.0pt" font-family="Courier New"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="342.0pt" before-indent="342.0pt" list-tab="0.0pt" font-family="Wingdings"/>
            </xdofo:list-template>
            <xdofo:list-template template-id="1232933599">
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 ." first-line-indent="-18.0pt" left-indent="36.0pt" before-indent="36.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#1 ." first-line-indent="-18.0pt" left-indent="72.0pt" before-indent="72.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#2 ." first-line-indent="-9.0pt" left-indent="108.0pt" before-indent="108.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#3 ." first-line-indent="-18.0pt" left-indent="144.0pt" before-indent="144.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#4 ." first-line-indent="-18.0pt" left-indent="180.0pt" before-indent="180.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#5 ." first-line-indent="-9.0pt" left-indent="216.0pt" before-indent="216.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#6 ." first-line-indent="-18.0pt" left-indent="252.0pt" before-indent="252.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="4" header-align="before" char-follow="tab" start-at="1" header-text="#7 ." first-line-indent="-18.0pt" left-indent="288.0pt" before-indent="288.0pt" list-tab="0.0pt"/>
               <xdofo:list-level format-code="2" header-align="after" char-follow="tab" start-at="1" header-text="#8 ." first-line-indent="-9.0pt" left-indent="324.0pt" before-indent="324.0pt" list-tab="0.0pt"/>
            </xdofo:list-template>
            <xdofo:list-template template-id="437288763">
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="8" header-text="#0" first-line-indent="-36.0pt" left-indent="36.0pt" before-indent="36.0pt" list-tab="36.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="2" header-text="#0 . #1" first-line-indent="-36.0pt" left-indent="36.0pt" before-indent="36.0pt" list-tab="36.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 . #1 . #2" first-line-indent="-36.0pt" left-indent="36.0pt" before-indent="36.0pt" list-tab="36.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 . #1 . #2 . #3" first-line-indent="-36.0pt" left-indent="36.0pt" before-indent="36.0pt" list-tab="36.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 . #1 . #2 . #3 . #4" first-line-indent="-54.0pt" left-indent="54.0pt" before-indent="54.0pt" list-tab="54.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 . #1 . #2 . #3 . #4 . #5" first-line-indent="-54.0pt" left-indent="54.0pt" before-indent="54.0pt" list-tab="54.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 . #1 . #2 . #3 . #4 . #5 . #6" first-line-indent="-72.0pt" left-indent="72.0pt" before-indent="72.0pt" list-tab="72.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 . #1 . #2 . #3 . #4 . #5 . #6 . #7" first-line-indent="-72.0pt" left-indent="72.0pt" before-indent="72.0pt" list-tab="72.0pt"/>
               <xdofo:list-level format-code="0" header-align="before" char-follow="tab" start-at="1" header-text="#0 . #1 . #2 . #3 . #4 . #5 . #6 . #7 . #8" first-line-indent="-90.0pt" left-indent="90.0pt" before-indent="90.0pt" list-tab="90.0pt"/>
            </xdofo:list-template>
            <xdofo:list-template template-id="352927263">
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="54.0pt" before-indent="54.0pt" list-tab="0.0pt" font-family="Symbol"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="o" first-line-indent="-18.0pt" left-indent="90.0pt" before-indent="90.0pt" list-tab="0.0pt" font-family="Courier New"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="126.0pt" before-indent="126.0pt" list-tab="0.0pt" font-family="Wingdings"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="162.0pt" before-indent="162.0pt" list-tab="0.0pt" font-family="Symbol"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="o" first-line-indent="-18.0pt" left-indent="198.0pt" before-indent="198.0pt" list-tab="0.0pt" font-family="Courier New"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="234.0pt" before-indent="234.0pt" list-tab="0.0pt" font-family="Wingdings"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="270.0pt" before-indent="270.0pt" list-tab="0.0pt" font-family="Symbol"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="o" first-line-indent="-18.0pt" left-indent="306.0pt" before-indent="306.0pt" list-tab="0.0pt" font-family="Courier New"/>
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="342.0pt" before-indent="342.0pt" list-tab="0.0pt" font-family="Wingdings"/>
            </xdofo:list-template>
            <xdofo:list-style style-id="7" template-id="1232933599"/>
            <xdofo:list-style style-id="6" template-id="1358501645"/>
            <xdofo:list-style style-id="5" template-id="437288763"/>
            <xdofo:list-style style-id="4" template-id="1544826743"/>
            <xdofo:list-style style-id="3" template-id="376322420"/>
            <xdofo:list-style style-id="2" template-id="352927263"/>
            <xdofo:list-style style-id="1" template-id="1500996035"/>
         </xdofo:list-styles>
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="48.6pt" margin-right="48.6pt" page-height="792.0pt" page-width="612.0pt" margin-top="22.5pt" margin-bottom="7.2pt">
               <fo:region-before region-name="region-header" extent="49.5pt"/>
               <fo:region-body region-name="region-body" margin-top="49.5pt" margin-bottom="64.8pt"/>
               <fo:region-after region-name="region-footer" extent="64.8pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(612.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(792.0)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(54.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(54.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(22.5)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(7.199997)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header">
               <fo:block xdofo:tab-stops="center:216.0pt:space right:432.0pt:space" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="0.0pt" text-align="start" widows="2" height="12.716001pt" font-size="11.0pt" font-family="Calibri"/>
               <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
               <xsl:for-each select=".//G_EMP_DETAILS_GROUP">
                  <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                  <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                  <fo:block xdofo:tab-stops="center:216.0pt:space right:432.0pt:space" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="0.0pt" text-align="start" widows="2" height="12.716001pt" font-size="11.0pt" font-family="Calibri"/>
               </xsl:for-each>
            </fo:static-content>
            <fo:static-content flow-name="region-footer">
               <fo:block xdofo:tab-stops="center:216.0pt:space right:432.0pt:space" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="0.0pt" text-align="start" widows="2"/>
            </fo:static-content>
            <fo:flow flow-name="region-body">
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt" font-size="11.0pt" font-family="Calibri"/>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt" font-size="11.0pt" font-family="Calibri"/>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt" font-size="11.0pt" font-family="Calibri"/>
               <fo:block xdofo:line-spacing="multiple:13.8pt" xdofo:xliff-note="TODAY_DATE" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt">
                  <fo:inline font-size="11.0pt" white-space-collapse="false" height="0.0pt" font-family="Calibri">
                     <xsl:value-of select=".//TODAY_DATE" xdofo:field-name="TODAY_DATE"/>
                  </fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt" font-size="11.0pt" font-family="Calibri"/>
               <fo:block xdofo:xliff-note="PERSON_NAME" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt">
                  <fo:inline font-size="11.0pt" white-space-collapse="false" height="13.09pt" font-family="Calibri" font-weight="bold">
                     <xsl:value-of select=".//PERSON_NAME" xdofo:field-name="PERSON_NAME"/>
                  </fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" xdofo:xliff-note="DEPARTMENT" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt">
                  <fo:inline font-size="11.0pt" white-space-collapse="false" height="0.0pt" font-family="Calibri" color="#000000">
                     <xsl:value-of select=".//DEPARTMENT" xdofo:field-name="DEPARTMENT"/>
                  </fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt" font-size="12.0pt" font-family="Calibri"/>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt">
                  <fo:inline font-size="12.0pt" white-space-collapse="false" height="0.0pt" font-family="Calibri" color="#000000" font-weight="bold" text-decoration="underline">Re: Probation Period</fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="justify" widows="2" height="0.0pt" font-size="12.0pt" font-family="Calibri"/>
               <fo:block xdofo:line-spacing="multiple:13.8pt" xdofo:xliff-note="PERSON_NAME" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="justify" widows="2" height="0.0pt">
                  <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="0.0pt" font-family="Calibri">Dear <xsl:value-of select=".//PERSON_NAME" xdofo:field-name="PERSON_NAME"/></fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" xdofo:xliff-note="DATE_PROBATION_END" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="justify" widows="2" height="0.0pt">
                  <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="0.0pt" font-family="Calibri">We wish to confirm that on <xsl:value-of select=".//DATE_PROBATION_END" xdofo:field-name="DATE_PROBATION_END"/> your probation period has been successfully completed. </fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" xdofo:xliff-note="BUSINESS_UNIT" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="justify" widows="2" height="0.0pt">
                  <fo:inline xml:space="preserve" font-size="12.0pt" white-space-collapse="false" height="0.0pt" font-family="Calibri">Your line manager is satisfied with the quality of your work and your contribution to the company and we also wish to thank you for your dedication to your responsibilities at <xsl:value-of select=".//BUSINESS_UNIT" xdofo:field-name="BUSINESS_UNIT"/>.</fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="justify" widows="2" height="0.0pt" font-size="12.0pt" font-family="Calibri"/>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt">
                  <fo:inline font-size="12.0pt" white-space-collapse="false" height="0.0pt" font-family="Calibri" color="#000000">Yours sincerely,</fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt" font-size="12.0pt" font-family="Calibri"/>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt" font-size="12.0pt" font-family="Calibri"/>
               <fo:block linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="6.0pt" text-align="start" widows="2" height="0.0pt">
                  <fo:inline font-size="12.0pt" white-space-collapse="false" height="13.872pt" font-family="Calibri" background-color="#ffff00">[Signatory]</fo:inline>
               </fo:block>
               <fo:block linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="6.0pt" text-align="start" widows="2" height="0.0pt">
                  <fo:inline font-size="12.0pt" white-space-collapse="false" height="13.872pt" font-family="Calibri" background-color="#ffff00">[Business Title]</fo:inline>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" linefeed-treatment="preserve" padding-top="0.0pt" orphans="2" end-indent="5.4pt" start-indent="5.4pt" padding-bottom="10.0pt" text-align="start" widows="2" height="0.0pt" font-size="11.0pt" font-family="Calibri">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
