<?xml version = '1.0' encoding = 'utf-8'?>
<!-- $Header: TEMPLATE_XXSC_XXSCPOANA_SGAPR_en_US.xsl 115.0 2016/05/23 09:25:39 xdouser noship $ -->
<!-- dbdrv: none -->

<!--Generated by Oracle BI Publisher 10.1.3.4.2-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="17.3pt" margin-right="17.3pt" page-height="595.35pt" page-width="1119.85pt" margin-top="22.7pt" margin-bottom="22.7pt">
               <fo:region-before region-name="region-header" extent="0.0pt"/>
               <fo:region-body region-name="region-body" margin-top="0.0pt" margin-bottom="0.0pt"/>
               <fo:region-after region-name="region-footer" extent="0.0pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(1119.85)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(595.35)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(22.699999)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(22.699999)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(22.7)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(22.7)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(22.7)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(22.7)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header"/>
            <fo:static-content flow-name="region-footer"/>
            <fo:flow flow-name="region-body">
               <fo:block xdofo:line-spacing="multiple:13.8pt" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-size="10.0pt" height="0.0pt" font-family="Arial"/>
               <fo:block xdofo:line-spacing="multiple:13.8pt" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.25pt" end-indent="5.4pt" padding-top="0.25pt">
                  <fo:table start-indent="-0.9pt" style-id="ts15" style-name="Table Grid" xdofo:align="start" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="63.0pt"/>
                     <fo:table-column column-width="46.9pt"/>
                     <fo:table-column column-width="56.0pt"/>
                     <fo:table-column column-width="48.3pt"/>
                     <fo:table-column column-width="74.2pt"/>
                     <fo:table-column column-width="66.45pt"/>
                     <fo:table-column column-width="57.4pt"/>
                     <fo:table-column column-width="90.3pt"/>
                     <fo:table-column column-width="50.4pt"/>
                     <fo:table-column column-width="65.05pt"/>
                     <fo:table-column column-width="66.5pt"/>
                     <fo:table-column column-width="58.9pt"/>
                     <fo:table-column column-width="64.9pt"/>
                     <fo:table-column column-width="64.9pt"/>
                     <fo:table-column column-width="64.9pt"/>
                     <fo:table-column column-width="64.9pt"/>
                     <fo:table-column column-width="76.95pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="13">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="12.0pt" font-family="Arial" white-space-collapse="false" font-size="12.0pt" font-weight="bold">Gulf Finance Corporation</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="12.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="13">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="center" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline background-color="#ffffff" font-weight="bold" color="#333333" font-size="13.0pt" height="13.0pt" white-space-collapse="false" font-family="Arial">PO Analysis Report - GFC UAE</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="13.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="13.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="13.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="13.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Date From :</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block xdofo:xliff-note="D_F" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                    <xsl:value-of select=".//CF_DATE" xdofo:field-name="CF_DATE"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="2">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline xml:space="preserve" height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Date To :</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block xdofo:xliff-note="D_T" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                    <xsl:value-of select=".//CF_DATE_TO" xdofo:field-name="CF_DATE_TO"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="2">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approved By:</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block xdofo:xliff-note="APP" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                    <xsl:value-of select=".//CF_APPROVER" xdofo:field-name="CF_APPROVER"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="2">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Date :</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block xdofo:xliff-note="Date" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                    <xsl:value-of select="xdoxslt:sysdate('DD-MON-YYYY  HH24:MI:SS')" xdofo:field-name="xdoxslt:sysdate('DD-MON-YYYY  HH24:MI:SS')"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Status:</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block xdofo:xliff-note="STS" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                    <xsl:value-of select=".//CF_STATUS" xdofo:field-name="CF_STATUS"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="2">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="2" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                           <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="top" height="0.0pt" number-columns-spanned="1" border-bottom="0.5pt solid #000000">
                              <fo:block height="10.0pt"/>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Number</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Type</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approval Status</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Order Date</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Supplier</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Currency</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Amount</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Closure Status</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Buyer</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approver 1</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approver 2</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approver 3</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approver 4</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approver 5</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approver 6</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approver 7</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Approver 8</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                        <xsl:variable name="_XDOFOTOTAL" select="count(.//G_PO_NUM_)"/>
                        <xsl:for-each select=".//G_PO_NUM_" xdofo:ctx="3">
                           <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                           <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                           <fo:table-row xdofo:repeat="R">
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="F, PO_NUM" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//PO_NUM_" xdofo:field-name="PO_NUM_"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="TYPE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//TYPE_LOOKUP_CODE" xdofo:field-name="TYPE_LOOKUP_CODE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="STATUS" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//AUTHORIZATION_STATUS" xdofo:field-name="AUTHORIZATION_STATUS"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="O_D" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CREATION_DATE" xdofo:field-name="CREATION_DATE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="SUP" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//VENDOR_NAME" xdofo:field-name="VENDOR_NAME"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="CUR" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CURRENCY_CODE" xdofo:field-name="CURRENCY_CODE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="middle" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AMT" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="right" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AMT" xdofo:field-name="CF_AMT"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="CLS_STS" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CLOSE_STATUS_" xdofo:field-name="CLOSE_STATUS_"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="SUPP" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//AGENT_NAME" xdofo:field-name="AGENT_NAME"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AP1" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AP1" xdofo:field-name="CF_AP1"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AP2" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AP2" xdofo:field-name="CF_AP2"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AP3" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AP3" xdofo:field-name="CF_AP3"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AP4" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AP4" xdofo:field-name="CF_AP4"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AP5" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AP5" xdofo:field-name="CF_AP5"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AP6" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AP6" xdofo:field-name="CF_AP6"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AP7" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AP7" xdofo:field-name="CF_AP7"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AP8, E1" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                    <fo:inline height="10.0pt" font-family="Arial" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//CF_AP8" xdofo:field-name="CF_AP8"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                        </xsl:for-each>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:13.8pt" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" font-size="10.0pt" height="0.0pt" font-family="Arial">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
