--------------------------------------------------------
--  DDL for Trigger XXSC_HR_EMP_CONT_ADDR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "APPS"."XXSC_HR_EMP_CONT_ADDR_TRG" 
BEFORE INSERT ON "XXSHINT"."XXSC_HR_EMP_CONT_ADDR_STG"
FOR EACH ROW
  DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
  XXSC_EMP_PKG.XXSC_CREATE_EMP_PHONE_EMAIL(
P_WINDOWS_LOGIN_ID   =>:NEW.WINDOWS_LOGIN_ID   ,
P_LOCALE        =>:NEW.LOCALE        ,
P_EMAIL_ADDRESS      =>:NEW.EMAIL_ADDRESS      ,
P_EMP_PHONE_NUMBER   =>:NEW.EMP_PHONE_NUMBER   ,
P_CONTACT_PHONE_NUMBER  =>:NEW.CONTACT_PHONE_NUMBER  ,
P_ADDRESS_LINE1         =>:NEW.ADDRESS_LINE1         ,
P_ADDRESS_LINE2         =>:NEW.ADDRESS_LINE2         ,
P_EMIRATES              =>:NEW.EMIRATES              ,
P_STREET                =>:NEW.STREET                ,
P_BUILDING             =>:NEW.BUILDING             ,
P_FLAT_NUMBER          =>:NEW.FLAT_NUMBER          ,
P_PO_BOX               =>:NEW.PO_BOX               ,
P_COUNTRY              =>:NEW.COUNTRY              ,
P_CONTACT_ADDRESS_LINE1 =>:NEW.CONTACT_ADDRESS_LINE1 ,
P_CONTACT_ADDRESS_LINE2     =>:NEW.CONTACT_ADDRESS_LINE2     ,
P_CONTACT_EMIRATES          =>:NEW.CONTACT_EMIRATES          ,
P_CONTACT_STREET            =>:NEW.CONTACT_STREET            ,
P_CONTACT_BUILDING          =>:NEW.CONTACT_BUILDING          ,
P_CONTACT_FLAT_NUMBER        =>:NEW.CONTACT_FLAT_NUMBER        ,
P_CONTACT_PO_BOX             =>:NEW.CONTACT_PO_BOX             ,
P_CONTACT_COUNTRY            =>:NEW.CONTACT_COUNTRY            ,
P_CONTACT_LAST_NAME          =>:NEW.CONTACT_LAST_NAME    ,
P_CONTACT_FIRST_NAME         =>:NEW.CONTACT_FIRST_NAME   ,
P_CONTACT_EMAIL_ADDRESS      =>:new.CONTACT_EMAIL_ADDRESS,
P_STATUS                     =>:NEW.STATUS,
P_ERROR_MESSAGE              =>:NEW.ERROR_MESSAGE,
P_BUSINESS_GROUP_ID          => :NEW.BUSINESS_GROUP_ID
);
  EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.PUT_LINE ('Error' || SQLERRM);
  END XXSC_HR_EMP_CONT_ADDR_TRG;
/
ALTER TRIGGER "APPS"."XXSC_HR_EMP_CONT_ADDR_TRG" ENABLE;
